### ISSUE TITLE
AgGridNg2.ngOnDestroy fails when not initialized

### ISSUE THREAD

**Issue by pendix** [ceolter/ag-grid-ng2#1]
When trying to access page with grid and route-based navigation is used to go away before rendering (router.navigateByUrl to a /login page on a protected page, in my case), the ngOnDestroy fails with
```
TypeError: Cannot read property 'destroy' of undefined
    at AgGridNg2.ngOnDestroy (http://127.0.0.1:3000/build/common.js:44400:20)
```

Please consider adding initialized check before api.destroy(), on agGrid2.js:
```
    AgGridNg2.prototype.ngOnDestroy = function () {
       if (this._initialised) {
          this.api.destroy();
       }
    };
```
Cheers!

**Comment by ceolter** [comment]
I will add that in. Thanks.

**Comment by ceolter** [comment]
i will do a release now, so you have this.
