### ISSUE TITLE
How to retrieve the old/previous value in inline editing?

### ISSUE THREAD

**Issue by sskmail14** [ceolter/ag-grid-ng2#100]
How to retrieve the old/previous value once after editing the data in a cell?

On Row click I have a service call to submit the data and if the data gets posted successfully then no problem and if not I have to revert to the old or previous values?

New data is available in data. What about the old data?

![image](https://cloud.githubusercontent.com/assets/5357908/21349886/71592a7c-c6da-11e6-8fe4-5124863332a2.png)

**Comment by seanlandsman** [comment]
You don't have access to the previous value once the edit is finished - if you need this then you'll need to store it before the edit is complete.

You can use the cellValueChanged event, which will have the new and old values available to you

**Comment by sskmail14** [comment]
Thanks @seanlandsman 
But can you see this issue in a different prespective,, I have a save button and cancel button in a column. If I click the save, but save fails then how can I maintain the each row data for this scenario?

**Comment by seanlandsman** [comment]
Hi @sskmail14 - going forward please post support questions in the forum: https://ag-grid.com/forum, where anyone in the team can help

For now though, what you're after is to not have the save apply until the save status come back, but this is not possible in the design of ag-grid. What you can do though is save the data in the grid an revert it asynchronously on the event of a failed save. 

When a save is finished the grid will either save it or not, there is no facility to conditionality save it, but you can achieve this with the above suggestion

**Comment by sskmail14** [comment]
Thanks @seanlandsman 

Few suggestions that can be taken.It could enhance the ag-grid as well.Please don't take it up as comparison.

1. Inline editing is working great, but need few enhancements - add, save and edit buttons as configurable for each row as like [ng2-smart-grid](https://akveo.github.io/ng2-smart-table/).
2. An inline form which has all the fields to be saved while clicking on a row which comes immediately after a row on inline edit(configurable) that makes more user-friendly.

If possible please return the old and new data.

**Comment by seanlandsman** [comment]
thanks for the feedback @sskmail14 - this is always welcome

**Comment by sskmail14** [comment]
Lot of Thanks @seanlandsman 
Please post a comment in this issue, if the enhancement is taken/done. So that will have a track of the same.
