### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by rezarr** [ceolter/ag-grid-ng2#101]
I downloaded the zip file from https://github.com/ceolter/ag-grid-ng2.
I am on a Mac.
when I run : npm run build, I get an error:

npm run build -debug

> ag-grid-ng2@7.0.1 build /Users/rrazavipour/Angular2/ag-grid-ng2
> ngc -p tsconfig-src.json && npm run clean-src && ngc -p tsconfig-main.json

Error at /Users/rrazavipour/Angular2/ag-grid-ng2/src/agGridColumn.ts:76:21: Duplicate identifier 'headerValueGetter'.
Error at /Users/rrazavipour/Angular2/ag-grid-ng2/src/ng2FrameworkFactory.ts:15:14: Class 'Ng2FrameworkFactory' incorrectly implements interface 'IFrameworkFactory'.
  Types of property 'setTimeout' are incompatible.
    Type '(action: any, timeout?: any) => void' is not assignable to type '(handler: any, timeout?: any) => number'.
      Type 'void' is not assignable to type 'number'.
Error at /Users/rrazavipour/Angular2/ag-grid-ng2/src/agGridNg2.ts:59:9: Type '{ globalEventListener: any; frameworkFactory: Ng2FrameworkFactory; }' is not assignable to type 'GridParams'.
  Types of property 'frameworkFactory' are incompatible.
    Type 'Ng2FrameworkFactory' is not assignable to type 'IFrameworkFactory'.
      Types of property 'setTimeout' are incompatible.
        Type '(action: any, timeout?: any) => void' is not assignable to type '(handler: any, timeout?: any) => number'.

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build" "-debug"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! ag-grid-ng2@7.0.1 build: `ngc -p tsconfig-src.json && npm run clean-src && ngc -p tsconfig-main.json`
npm ERR! Exit status 1

Any ideas what the issue is here?
[npm-debug.log.txt](https://github.com/ceolter/ag-grid-ng2/files/667575/npm-debug.log.txt)

**Comment by seanlandsman** [comment]
Hi,

I've answered this via email, but for completeness: 

master is generally subject to regular changes and is often (as in this case) dependent on changes to master in ag-grid or ag-grid-enterprise.

If you want to build ag-grid-ng2 either pull the last released version down, or try tomorrow as we'll be doing a release later today which will bring master back into line across the board.

Note that if you want to use ag-grid-ng2, you don't actually need to build it to use it - just pull down the latest released dependency from either npm or bower.

thanks,
