### ISSUE TITLE
Is there any function to destroy the EditorComponent(AgEditorComponent)

### ISSUE THREAD

**Issue by sskmail14** [ceolter/ag-grid-ng2#103]
Am using the cellEditorFramework to have a popup.
It closes when I click outside the cell or focus on another cell.
Is there any way to close the popup on clicking any part of the popup?

**Comment by seanlandsman** [comment]
if you take a look at the editor example (https://github.com/ceolter/ag-grid-ng2-example/blob/master/app/editor-component.component.ts) you'll find that the MoodEditor closes on enter. You can do something similar, but when the click event is fired use api.stopEditing() to stop editing the cell

**Comment by sskmail14** [comment]
Thanks @seanlandsman It works
