### ISSUE TITLE
zone.js  ^0.7.x needed for Angular 2.3.1+

### ISSUE THREAD

**Issue by AilisObrian** [ceolter/ag-grid-ng2#104]
zone.js  ^0.7.x needed for Angular 2.3.1+ at peerDependencies.

**Comment by seanlandsman** [comment]
You can still specify and use 0.7.x in your project if you want to, but this component works with 0.6.x and above. If we specify 0.7.x it will force clients to upgrade, even if they dont want to

**Comment by AilisObrian** [comment]
@seanlandsman then, why don't we change ^0.6.x to >=0.6.x

```javascript
> semver = require('semver')
> semver.satisfies('0.7.2', '>=0.6.x')
true
> semver.satisfies('0.7.2', '^0.6.x')
false
```

**Comment by AilisObrian** [comment]
I really want to apply this for shrinkwrapping our packages and deploying more reliably.

**Comment by seanlandsman** [comment]
hi @AilisObrian - I'll be looking at this this week, with a view to doing a patch release to resolve this for you

**Comment by seanlandsman** [comment]
@AilisObrian I've released 7.1.2-beta.1 that includes this (amongst other minor changes) - please try it out and let me know if it solves this for you

**Comment by AilisObrian** [comment]
@seanlandsman 7.1.2-beta.1 Works well! Thanks you!!!!

**Comment by seanlandsman** [comment]
@AilisObrian thanks - we'll do a full release later in the week (will be 7.1.3) to resolve this
