### ISSUE TITLE
Refresh Data on click button

### ISSUE THREAD

**Issue by robigit** [ceolter/ag-grid-ng2#105]
I have used  the ag-grid-ng2 in Angular2. It works perfectly except for one thing: If I assign gridOptions.rowData in the constructor of the component, I see the data correctly but if I assign the data on a click event, the grid remains empty.
I tried even to put gridOptions.api.RefreshView() but nothing has changed.
Do you have any suggest?

Thank you

**Comment by seanlandsman** [comment]
gridOptions.rowData is set and read once - once set it won't be read again so if you make changes to it the grid will not be aware of them.

For dynamic changes please use gridOptions.api.setRowData instead

**Comment by robigit** [comment]
Now it works! Thank you very much
