### ISSUE TITLE
cellRenderer is not binding click event

### ISSUE THREAD

**Issue by elaijuh** [ceolter/ag-grid-ng2#106]
I want to render a button into the cell with `cellRenderer` like this

```
{
        headerName: 'Actions',
        minWidth: 200,
        cellRenderer(params) {
            return `
              <button (click)="editAWSAccess()">
                <span class="fa fa-edit">Edit</span>
              </button>
            `
        }
}
```

I have `editAWSAccess` class method for my component, but I found the click event is not triggered. Do I need to manually register a listener to the click event in cellRenderer?

I saw a work around to use `onRowClicked` which is not quite beautiful

**Comment by seanlandsman** [comment]
What you're using isnt for this component (ag-grid-ng2) - its just a function. See https://www.ag-grid.com/javascript-grid-cell-rendering/ for more information about your options, but if you want to use angular 2 take a look at this page, but also the angular 2 documentation: https://www.ag-grid.com/best-angular-2-data-grid/

**Comment by lucashfreitas** [comment]
Hello @elaijuh. Did you find any solution for that? I'm facing the same problem and it seems that angular ag grid does not provide any documentation for how to bind angular click events in cell renderer function.

**Comment by AGSTRANGER** [comment]
Hello everyone, I have found a solution. Simply set-up a custom Cell Renderer component. Here's an example:
import { Component} from '@angular/core';
import {RattachementToDepartement} from'../services/rattachementToDepartement.service';

```
@Component({
  selector: 'app-rattachements-cell-renderer',
  templateUrl: './rattachements-cell-renderer.component.html',
  styleUrls: ['./rattachements-cell-renderer.component.css']
})
export class RattachementsCellRendererComponent {
  /**PS THE FOLLOWING CODE IS CRUCIAL FOR THE CELL RENDERER TO WORK */
  params: any;
  agInit(params: any): void {
    this.params = params;
  }
 
  public populateListInColTwo(chosenOption) {
    // I added the following line because without it the colTwoList gets all the accumulated chosen lists
    this.colTwoList = [];
    if (chosenOption.value === 'Audit') {
    
    } else if (chosenOption.value === 'RA') {
   
    } else if (chosenOption.value === 'Consulting') {
   
    } else if (chosenOption.value === 'FA') {

}
    else if (chosenOption.value === 'Tax&Legal') {
    }
    else if (chosenOption.value === 'ICS') {

    }
    else if (chosenOption.value === 'Taj') {
    }
  }
}
```
`<hr>

<select class="form-control" (change)="populateListInColTwo($event.target)">
  <hr>
  <option id="1"></option>
  <option id="1">Audit</option>
  <option id="2">RA</option>
  <option id="3">Consulting</option>
  <option id="5">FA</option>
  <option id="5">Tax&Legal
  </option>
  <option id="6">ICS</option>
  <option id="7">Taj</option>
</select>
<hr>
`

**Comment by progmars** [comment]
This doesn't help to pass click events from inside the RattachementsCellRendererComponent  to the outer component (controller). But I guess we can pass click handlers for buttons through params.
