### ISSUE TITLE
How to filter JSON datatype?

### ISSUE THREAD

**Issue by sskmail14** [ceolter/ag-grid-ng2#107]
For a row I have a nested JSON where I render the nested JSON using cellRendererFramework, but need to know how to SEARCH/FILTER based on any of the nested json property?

_**Example**_
```
{
     name:"Gilly",
     age:34,
     details:{
                   driving-licence-number:123123123123,
                   passport-number:098203982039802
                }
}
```

**_Ag Grid Columns_**
```
______________________________________
|Name     | Age | Detials              |
______________________________________
|Gilly    |  34 |  DL:123123123123     |
|         |     |  PN:098203982039802  |
______________________________________
```

How do I search for **_Details_** column?

**Comment by seanlandsman** [comment]
hi @sskmail14 - please post support questions on either the forums (https://ag-grid.com/forum) or stackoverflow/gitter.

GitHub issues should be reversed for issues/enhancements etc

**Comment by sskmail14** [comment]
Thanks @seanlandsman !!!

If I try to register in the forum you specified above the registration mail is not dropping in my inbox - can't able to register. That's why am raising the issues here.

**Comment by seanlandsman** [comment]
let me know your forum username - I'll check it out

**Comment by sskmail14** [comment]
Thanks @seanlandsman 
Username - sskmail14

**Comment by seanlandsman** [comment]
@sskmail14 I've activated your account - you should be able to post to the free forum now

**Comment by sskmail14** [comment]
@seanlandsman  Thanks it works!!!!
