### ISSUE TITLE
angular and cli supported versions

### ISSUE THREAD

**Issue by feloy** [ceolter/ag-grid-ng2#110]
Hi, 
I've a lot of troubles upgrading to latest versions of angular (2.4.1) and angular-cli (beta.24) for my project using ag-grid-ng2.

What are the latest supported versions?

**Comment by seanlandsman** [comment]
I cant see why it shouldnt work with both of these - wht errors are you seeing? Do you have a build config you can share so I can try reproduce and resolve?

**Comment by seanlandsman** [comment]
also checkout the latest examples project - there is a example using angular cli now too

**Comment by feloy** [comment]
Thanks, I'll try to investigate more to isolate the problem.


Le 2 janvier 2017 18:21:36 GMT+01:00, seanlandsman <notifications@github.com> a écrit :
>I cant see why it shouldnt work with both of these - wht errors are you
>seeing? Do you have a build config you can share so I can try reproduce
>and resolve?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ceolter/ag-grid-ng2/issues/110#issuecomment-269998903

-- 
Philippe MARTIN

**Comment by feloy** [comment]
I finally got it up and running with latest angular and angular-cli. It seems that it was an incompatibility with some package not updated due to an outdated yarn.lock. I don't understand why a got errors about AgGridModule loading...

Thanks again for your support, I close the issue.
