### ISSUE TITLE
Issue with dynamic columns when more than one grid is in the page

### ISSUE THREAD

**Issue by phillipebarbosa** [ceolter/ag-grid-ng2#114]
Hi,

I am facing a problem when I need to create columns dynamically (using angular2 components as renderer) and more than one ag-grid-ng2 is in the page. When a create the columns, they are binded to the latest ag-grid-g2 component (viewContainerRef) that has been loaded.

This is a problem for me because I have a scenario that I create multiple grids, but only load the columns of the first grid in the end. So when I dynamically create the columns of the first grid, all the Renderer Components are binded to the latest grid. As all the grids are inside a Modal except by the first grid, when I close the modal, all the other grids are destroyed with the Renderer components and the events that I have inside this components.

As I know this could be difficult to understand, I have created an app to reproduce the problem. The steps are in the page:
[ag-grid-ng2 viewContainerRef.zip](https://github.com/ceolter/ag-grid-ng2/files/704814/ag-grid-ng2.viewContainerRef.zip)

This problem is caused (in my opinion) because the Ng2FrameworkFactory is a singleton and it has the reference to the ag-grid-ng2 instance (viewContainerRef). So, every time a ag-grid-ng2 is created, it overrides the last viewContainerRef. Also, the setColumnDefs function uses the viewContainerRef provided by the Ng2FrameworkFactory.

**Comment by seanlandsman** [comment]
hi - I'll take a look at this early next week - thanks for providing an example, this will help me reproduce and fix that much quicker

**Comment by seanlandsman** [comment]
hi @phillipebarbosa - I've taken a quick look and see what you mean. I'll focus on this early next week, with a view to having a fix for our next release

**Comment by seanlandsman** [comment]
issue raised as AG-197 in our pipeline/backlog: https://www.ag-grid.com/ag-grid-pipeline/

**Comment by phillipebarbosa** [comment]
Great! Thank you, @seanlandsman!

**Comment by seanlandsman** [comment]
@phillipebarbosa finally looking at this today - sorry for the delay

**Comment by seanlandsman** [comment]
this has now been fixed - it will be available in the next release (8.0.0 to be released this week)

thanks @phillipebarbosa for such a thorough working example of the problem - made it much easier to fix!

**Comment by phillipebarbosa** [comment]
@seanlandsman thank you for your help!!!

**Comment by anilcrest** [comment]
where can I find this solution? when i generate dynamic multiple grid in angular4 that time it's always set last grid row data.

**Comment by pmdserrano** [comment]
@anilcrest, did you find a solution for your problem?
