### ISSUE TITLE
Ag-Grid issue with Angular2 Tabs

### ISSUE THREAD

**Issue by imanagemyschool** [ceolter/ag-grid-ng2#115]
We are having an issue in refreshing the ag-grid data in a angular2 tabset. The issue is that the data doesn't get refreshed automatically.

i.e, I have an event like below:

<select class="form-control" [(ngModel)]="selectedId"  (ngModelChange)="getData()">

The above event will fetch some data from back end and display it on a tab. If I select a tab, and then change the above event the new data doesn't get refreshed in the grid. It still shows the old data.

**Comment by seanlandsman** [comment]
I need some more information here - how are you setting the data in the grid?

**Comment by imanagemyschool** [comment]
Thanks for the response. 

In fact the issue is that I wasn't setting the data correctly. Once I updated the code to the below code, it started working:

this.gridOptions.api.setRowData(newDataFromBackEnd)

Closing the issue..
