### ISSUE TITLE
AOT issue

### ISSUE THREAD

**Issue by ghaiat** [ceolter/ag-grid-ng2#116]
Hello,
i m having the following error when running aot with the latest version:

Failed to read JSON file xxxx/node_modules/ag-grid-ng2/dist/aggrid.module.metadata.json

can you remove the comment you added at the top with the version number?
it makes the json not valid

Cheers

**Comment by ghaiat** [comment]
it s actually the case for all the .metadata.json in dist

**Comment by ghaiat** [comment]
can your replace in the gulp file 
gulp.src('./dist/*') =>     gulp.src(['./dist/*', '!./dist/**/*.metadata.json'])
?

**Comment by EndarValuk** [comment]
Additionally, one more trouble while building ng-grid2.
JSON files(*.metadata.json) must be in UTF8.
Reference angular/angular-cli#3970

**Comment by seanlandsman** [comment]
@ghaiat Fixed in 7.2.2 - thanks for reporting

@EndarValuk - the default charset is utf8 and looking at the metadata files they appear to be utf8 - are you saying they're not?

**Comment by EndarValuk** [comment]
@seanlandsman updated to 7.2.2 and problem is missing. Perhaps my local npm_packages was messed.
Anyway, TX for fast fix.
