### ISSUE TITLE
Type '{ rowHeight: number; rowModelType: string; rowSelection: string; suppressCellSelection: true; pag...' is not assignable to type 'GridOptions'.

### ISSUE THREAD

**Issue by ianhzhang** [ceolter/ag-grid-ng2#118]
Not problem with 
ag-grid: 7.1.0
ag-grid-ng2: 7.1.2

When I upgrade to 7.2.1, I have see following error:
Type '{ rowHeight: number; rowModelType: string; rowSelection: string; suppressCellSelection: true; pag...' is not assignable to type 'GridOptions'.

**Comment by seanlandsman** [comment]
This was an issue in core, since fixed: https://github.com/ceolter/ag-grid/issues/1418
