### ISSUE TITLE
internal angular properties not recognized in doesExternalFilterPass

### ISSUE THREAD

**Issue by TheILPlace** [ceolter/ag-grid-ng2#121]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **ag-grid-ng2 version:** 2.0.X

7.2
* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

7.2
* **Angular version:** 2.0.X

2.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

related to :
http://stackoverflow.com/questions/37957310/ag-grid-external-filter-in-angular-2-filter-presents-but-grid-not-updating

i am using a custom filter, using isExternalFilterPresent and doesExternalFilterPass
in the component that holds the ag-grid, i have a property that indicated if the filter should be applied or not. a simple boolean peoperty.
that property's value isnt recognized in eitner above functions. the property returns "undefined".
thus, forcing me to use the solution as described in stackoverflow, and get the value from the HTML element (a checkbox in my case)

var newValue = (<HTMLInputElement>document.getElementById("portDropdownMenu")).value

any help is appreciated to figure out if this is by design or a bug

**Comment by seanlandsman** [comment]
Although the SO link is helpful, I cannot run it (or see the whole code) so am a bit limited in what help I can offer here.

Everything in the component should be available to you - the only thing I can think of here is that you've a closure of some sort somewhere causing "this" to not be what you expect it to be

A repro will help me find the problem you're having here

**Comment by TheILPlace** [comment]
hi,
i've downloaded the ng2 samples from your github. the cli version.

in the from-rich-component.ts i made the following changes:

in the class declaration, add:
//add this
    public testFilter:string;

in the constructor:

        //add this
        this.testFilter = "TEST";
        this.gridOptions.isExternalFilterPresent  = this.isExternalFilterPresent;
        this.gridOptions.doesExternalFilterPass = this.doesExternalFilterPass;
    
in the class iteself, add this:

private isExternalFilterPresent():boolean{
        console.log(this.testFilter);
        return true;
       }

     private doesExternalFilterPass(node){
        console.log(this.testFilter);
        return true;
       }

if you look at the console, the output in both cases is "undefined".

i've tried to add something to the context property, for example, in the constructor:
this.gridOptions.context.testFilter = "1";

and then in both functions above try to access it - still -  undefined.
[from-rich.component.ts.txt](https://github.com/ceolter/ag-grid-ng2/files/740514/from-rich.component.ts.txt)

**Comment by seanlandsman** [comment]
Ok, this is just a javascript function "this" issue - when when the functions are called "this" isnt the containing class, it's some undefined value.

If you want this to be the containing class then you'll need this instead:

        this.gridOptions.isExternalFilterPresent  = this.isExternalFilterPresent.bind(this);
        this.gridOptions.doesExternalFilterPass = this.doesExternalFilterPass.bind(this);

**Comment by TheILPlace** [comment]
thank you so much for this !!!

**Comment by jiayihu** [comment]
I think this should be made more clear in the documentation because people are used to think component methods will have `this` set as a reference to the component instance.

For example I declared `doesExternalFilterPass` as following with a long comment to explain it because surely someone else will be confused and may miss it:

```typescript
/**
   * This property is an arrow functions, which binds `this` to the Angular Component.
   * It's necessary otherwise `this` is undefined inside the function because
   * it's not called as a method of the class by the Datagrid.
   * It's called as `doesExternalFilterPass(node)` and not as `component.doesExternalFilterPass(node)`
   */
  doesExternalFilterPass = (node: RowNode): boolean => {
    return node.data.currency >= this.currencyFilter;
  }
```

**Comment by eugene159** [comment]
This is crazy, I had the same issue and spent a day trying to solve it until I found this discussion. Class variable became undefined without any reason inside isExternalFilterPresent() method.
bind(this) solved it. Thank you!

**Comment by TheILPlace** [comment]
glad this could help you out !

**Comment by seanlandsman** [comment]
@eugene159 @jiayihu 

I'm sorry you've been stung by this, but as I said above this is not a grid or even angular issue - this is a simple javascript scoping issue and will occur anytime you specify a function within an object that relies on "this"

**Comment by eugene159** [comment]
In Angular you don't use "function" keyword, isExternalFilterPresent() looks like a regular public method, like hundreds of other methods in my project and "this" inside such methods always refers to a component class, this is why I didn't expect a trick here. But I understand what you are talking about. Inside a function(){ } "this" changes it's context, this is why we use ()=> syntax now.

**Comment by jiayihu** [comment]
@seanlandsman Yup I know about the technical reasons behind it, I was just suggesting making it more clear in the documentation since it's easy to forget about `this` binding in Angular

**Comment by king612** [comment]
Thank you @seanlandsman  for posting the .bind() solution.  Hadn't seen that trick before.  I had been breaking my head on this trying all kinds of goofy workarounds.  This, and also many thanks to others for the reminder on using arrow function syntax to solve it perhaps a little more elegantly.  This (no pun intended) solves a major irritant I've been having trying to integrate in third party tools into Angular/TypeScript code.

Also, I heartily agree with @jiayihu - this should definitely be called out in the ag-grid documentation about using the grid in Angular/TypeScript.  There's no mention of the scoping pitfall in there at all that I've seen in the Angular section about integrating ag-grid into TypeScript environments.

Thank you all!
