### ISSUE TITLE
notsup Not compatible with your operating system or architecture: fsevents@1.0.17

### ISSUE THREAD

**Issue by dylanjmcdonald** [ceolter/ag-grid-ng2#122]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ag-grid and ag-grid-ng2 will not install in angular2 application generated with angular-cli. Receiving the following error after running `npm install`

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.17
```

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10, npm 3.10.3

* **ag-grid-ng2 version:** 2.0.X
latest

* **ag-Grid/ag-Grid-Enterprise version:** 2.0.X

* **Angular version:** 2.0.X
angular-cli: 1.0.0-beta.26
node: 6.9.2
os: win32 x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by dylanjmcdonald** [comment]
Disregard. Non-issue.

**Comment by jegjessing** [comment]
Well, it is an issue for me.. Why do did you change it?
Did you make an error that I also made?

**Comment by dylanjmcdonald** [comment]
> Well, it is an issue for me.. Why do did you change it?
Did you make an error that I also made?

Hmm, I don't recall exactly - it might have had something to do with running an `npm install` on different machines. I don't think the warnings prevented the library from working for me though.
