### ISSUE TITLE
Scroll bars not working in IE11 when using ag-grid with angular2

### ISSUE THREAD

**Issue by srivastgithub** [ceolter/ag-grid-ng2#123]
[* ] bug report => search github for a similar issue or PR before submitting 

**Please tell us about your environment:**
 Windows

Angualar 2 Project 
* **ag-Grid version:** X.X.X

   "ag-grid": "^6.2.1",
   "ag-grid-ng2": "^6.2.0"

as well as 
  "ag-grid": "^7.2.2",
  "ag-grid-ng2": "^7.2.2", 

* **Browser:**
 IE11

* **Language:** 
Typescript "1.8.11" ,"2.1.5",ES5

**Current behavior** 
 I am using ag-grid with angular2 .The vertical scroll bars works fine in chrome but in IE the scroll bar is visible but can't click on up  or down arrow in the scroll bar .I have ag-grid vesions as below in my packages.json 
 "ag-grid": "^6.2.1",
 "ag-grid-ng2": "^6.2.0", 

But i have tried with the latest versions of both with latest tsc and node .The behavior is same.

In another post i saw something about making display:none in this css class
.ag-full-width-viewport {
  height: 100%;
  width: 100%;
  position: absolute;
  top: 0px;
  left: 0px;
  display: inline;
  pointer-events: none;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  overflow: hidden;
}
 
and i tried that too .It still does not work .Please help .This is an important issue.The client uses IE.I dont want to change the grid at this time 

 

**Expected behavior**
I should be able to scroll
![scroll behavior](https://cloud.githubusercontent.com/assets/7807082/22490448/6439d65c-e7eb-11e6-8a73-7c97a093ff7e.PNG)

**Comment by seanlandsman** [comment]
We are unable to reproduce this - can you supply a plunker for us to investigate?

**Comment by srivastgithub** [comment]
Thank you very much for responding 

It will be hard to give a plunker right now but I think i have found whats causing it.When  i set   the columns property  pinned:'left' or 'right' this behavior comes.In fact i can reproduce this in  the example files which you have provided in the git hub .*ag-grid-ng2-example*. In the details panel (file  
\angular-cli\src\app\detail-panel.component.ts) if i change the column definitions to include pinned:'left' ,I can reproduce the behavior.
The horizontal bar does not show up at all and the vertical is  inactive 
 
``` 
    private createColumnDefs() {
        return [{headerName: 'Call ID', field: 'callId', cellClass: 'call-record-cell',pinned:'left'},
            {headerName: 'Direction', field: 'direction', cellClass: 'call-record-cell' ,pinned:'left'},
            {headerName: 'Number', field: 'number', cellClass: 'call-record-cell',pinned:'left'},
            {
                headerName: 'Duration',
                field: 'duration',
                cellClass: 'call-record-cell',
                cellFormatter: this.secondCellFormatter,pinned:'left'
            },
            {headerName: 'Switch', field: 'switchCode', cellClass: 'call-record-cell',pinned:'left'}];

    } 
```

 The same grid i threw on my application page lay out and u can see that the scroll bar is not active.Works fine in chrome
![image](https://cloud.githubusercontent.com/assets/7807082/22530803/81e6712c-e8ab-11e6-94c7-aca3ece52205.png)


And the following snip is directly from the example .Again by setting pinned:'left' for all the columns

![image](https://cloud.githubusercontent.com/assets/7807082/22531055/bb2c4eba-e8ac-11e6-8d59-fb0cf34dacc1.png)

**Comment by ceolter** [comment]
reproduced and verified.

this is nothing to do with ng2 - it happens on IE 11 using standard demo, if you pin all columns of grid to the left.

when pinning left the pinned section has no vertical scrolls. it's the main body that does the scrolling
always. the pinned columns picks up the mouse wheel - but then forwards the scroll request to the body - but there is no body to scroll.

a grid with only pinned columns makes no sense, so i don't see this as a realistic issue. if it is, the fix would be hacky and complex. given this is an edge case, effort vs reward is badly weighted. so putting this into category of 'dont fix'.

suggestion - always have at least one col not pinned if you want it to work.

**Comment by srivastgithub** [comment]
Ok thanks for looking .
