### ISSUE TITLE
How to bind the cellEditorParams cellRendererParams and resetting cellEditorParams cellRendererParams based on the selection in ag-grid

### ISSUE THREAD

**Issue by sskmail14** [ceolter/ag-grid-ng2#124]
**I'm submitting a issue/enhancement**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

1.cellEditorParams or cellRendererParams is common to all the rows of a columns as of now.
2.The change of value should trigger a change to the another cell of the same row.
    Example: I am having two columns in a table 
                    ---- 1.Continent[drop-down]
                   ----  2.Country[drop-down]
   If I change the value of the Continent drop-down then the respective state of the same row should get reset.
**Expected behavior**

Can cellEditorParams or cellRendererParams  be specific to each row?
**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows 7 64-bit
* **ag-grid-ng2 version:** 7.2.2

* **Angular version:** 2.4.1

* **Browser:** All

* **Language:** TypeScript

Link that I have raised a question in [stackoverflow](http://stackoverflow.com/questions/42048483/how-to-bind-the-celleditorparams-cellrendererparams-and-resetting-celleditorpara).

**Comment by seanlandsman** [comment]
Please dont use github for support queries

**Comment by sskmail14** [comment]
Oh Sorry can you have a look at the question being propmpted in stackoverflow??? 
**Link:**
 [http://stackoverflow.com/questions/42048483/how-to-bind-the-celleditorparams-cellrendererparams-and-resetting-celleditorpara](http://stackoverflow.com/questions/42048483/how-to-bind-the-celleditorparams-cellrendererparams-and-resetting-celleditorpara)?
