### ISSUE TITLE
HeaderComponents fail to scroll rows to the correct position

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid-ng2#127]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If you're using the new headerComponentFramework and include an input in it, tabbing through the headers doesn't scroll the rows properly and sometimes even fails to render parts of the rows completely.

**Expected behavior**
Tabbing through headers behaves the same as tabbing through a row by scrolling correctly.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/FLmZTqvBI9d8o5OT7jAr?p=preview
Open this plunker, click in the input of the first header and tab twice. The focus should be in the input of the 3rd header but the row didn't scroll. Clicking back into the first header also doesn't scroll the headers back.

**What is the motivation / use case for changing the behavior?**
I'm adding a switch to the grid that enables a configuration mode. By default drag and drop and co are disabled. Enabling this mode enables column drag and drop, changing the width and changing the column headers by swapping them with inputs (or rather changing the header component from default to my custom one) and binding these to the headerName property.

**Please tell us about your environment:**

Windows 7, VSCode 1.9.1, NPM 3.10.6

* **ag-grid-ng2 version:** 8.0.0

* **ag-Grid/ag-Grid-Enterprise version:**8.0.1

* **Angular version:** 2.4.1

* **Browser:** all

* **Language:** TypeScript 2.1.6

**Comment by seanlandsman** [comment]
Hi Stephen - thanks for reporting. I've moved your issue to the ag-grid repo here: https://github.com/ceolter/ag-grid/issues/1471

I suggest you watch that issue going forward for updates on its status

thanks
