### ISSUE TITLE
[Feature Request] isPopup support for header components

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid-ng2#128]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/ceolter/ag-grid-ng2/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**
isPopup has it's drawbacks but it's required to properly show custom components that extend outside of a cell (in this case a typeahead with a potentially long list of options). This same is obviously true for header components. Currently my typeahead in the header gets cut of by the overflow settings of the grid and isPopup would solve that, including other problems/use cases.

* **ag-grid-ng2 version:** 8.0.0

* **ag-Grid/ag-Grid-Enterprise version:** 8.0.1

* **Angular version:** 2.4.1

* **Browser:** [all]

* **Language:** [all]

**Comment by seanlandsman** [comment]
Hi Stephen,

Thanks for the suggestion - created a new issue here: https://github.com/ceolter/ag-grid/issues/1472

thanks
