### ISSUE TITLE
Grid Api becomes unavailable when component containing grid inside is re-rendered.

### ISSUE THREAD

**Issue by ASHFAQPATWARI** [ceolter/ag-grid-ng2#129]
![api-undefined](https://cloud.githubusercontent.com/assets/5632217/22922340/6e679ace-f2ae-11e6-8844-2d06a1531f97.png)
**I'm submitting a ...** 
```
[x] bug report
```

**Current behavior**

I have a ag-grid-ng2 inside a component. I use this component in multiple places in my application. Once the component containing the grid gets re-rendered because of either route navigation or *ngIf, then the gridOptions api gets null. So I cannot use the grid API for anything.

**Expected behavior**

Grid API should be available

**Please tell us about your environment:**

* **ag-grid-ng2 version:** 8.0.1

* **ag-Grid/ag-Grid-Enterprise version:** 8.0.0

* **Angular version:** 2.4.7

* **Browser:** [all]

* **Language:** [all]

**Comment by seanlandsman** [comment]
A plunker would be helpful here - without anything to go on we're unlikely to be able to reproduce this easily

**Comment by osmolyar** [comment]
Seeing a very similar issue https://stackoverflow.com/questions/57147736/ag-grid-defaultcoldef-not-re-applied-after-initial-component-load  - it's not that the gridApi is unavailable entirely (gridApi.sizeColumnsToFit still works, for instance) but gridOptions,defaultColDef doesn't get applied after re-rendering.
