### ISSUE TITLE
Unable to use it with angular 2.0.0-rc2

### ISSUE THREAD

**Issue by arpit-agarwal** [ceolter/ag-grid-ng2#13]
The peer dependency specified in package.json should be liberal to allow minor version upgrade of angular.

npm ERR! peerinvalid Peer ag-grid-ng2@4.2.0 wants @angular/core@2.0.0-rc.1

It should support upgrade to @angular/core@2.0.0-rc.2

**Comment by seanlandsman** [comment]
Hi

This has been updated in both this and the example project - it'll be rolled out in the next release

thanks
