### ISSUE TITLE
Unable to use ag-grid bundle in angular 2 application

### ISSUE THREAD

**Issue by arpit-agarwal** [ceolter/ag-grid-ng2#15]
I have update my system.config.js to use ag-grid bundle like this 
`    'ag-grid': 'vendor/ag-grid/dist/ag-grid.js',`
But ag-grid-ng2 has nested import for main from ag-grid like
`import { GridApi, ColumnApi } from 'ag-grid/main' `

This was causing error while using ag-grid as a bundle. I have taken liberty to fork  of the repo and update the import as below and used npm link to get bundle bulking for my project
`import { GridApi, ColumnApi } from 'ag-grid'`

It would be great if that changes could be merged or have a separate bundle.js in ag-grid-ng2 to allow bundle uses for ag-grid.

forked repo with fix: https://github.com/arpit-agarwal/ag-grid-ng2

**Comment by arpit-agarwal** [comment]
@ceolter @seanlandsman  please provide your inputs for this

**Comment by ceolter** [comment]
we won't be providing ng2 bundle, to few people require it for us to be supporting it.
