### ISSUE TITLE
How to use bootstrap dropdown(ng2-bootstrap) in ag-grid-ng2

### ISSUE THREAD

**Issue by erashu212** [ceolter/ag-grid-ng2#16]
@ceolter ,

I am not getting way to implement ng2-bootstrap dropdown in ag-grid-ng2.

Thanks,
Ashutosh

**Comment by erashu212** [comment]
Hi @ceolter @seanlandsman ,

Any update on this?

**Comment by ceolter** [comment]
no update.

**Comment by erashu212** [comment]
@ceolter : Do you have any way to make this thing working?

**Comment by ceolter** [comment]
we don't use ng2-bootstrap, so would have to invest time looking into it,
but we don't have spare time.

**Comment by drnknmstrr** [comment]
+1

**Comment by seanlandsman** [comment]
I took a brief look at this today, and as it stands ng2-bootstrap doesnt build or run - given this we probably wont be able to spend any time adding any examples for this.

Its something we can possible look at again in the future

**Comment by Adondriel** [comment]
Reopen this please? It would be very nice if this grid gave us this functionality by default. Very frustrating that you only provide text and select options for editing the grid. Specifically, I would like to have access to a datepicker, from ng2-bootstrap within the ag-grid.
