### ISSUE TITLE
last row missing, when data loaded async

### ISSUE THREAD

**Issue by Muenchen-Michi** [ceolter/ag-grid-ng2#18]
Hi,

when I load the rowData from my api using http.get, the last row will not be shown in the grid.
`this.http.get(apiurl).map(res => res.json()).subscribe((data) => {this.rowData=data.data;})`
I query my api in the constructor, but also tried it in ngOnInit without success.

this.rowData has 7 rows and even if I debug the gridData in onModelUpdated, I have 7 rows in rowsToDisplay, but only the first 6 will be displayed. I checked the DOM and there are also just 6 rows in the grid.

But when I click on the filter-menu in the grid, the last row appears. I don't have to enter any text, just clicking the menu-icon.

I'm using angular 2.0.0-rc.3, ag-grid 5.0.0-alpha.2 and ag-grid-ng2 5.0.0-alpha.0

**Comment by ceolter** [comment]
can you reproduce in any demo? or if not, i need something else to go on, such as plunker. as the grid is working as expected in my tests.

**Comment by Muenchen-Michi** [comment]
Here's the [plunker](http://embed.plnkr.co/lpslW0V8BuD9MarL1fZy/).

When building the plunker I found out, that this problem has to do with ng2-bootstrap, if ag-grid is on a non-visible tab.

So when you start the plunker and switch to "Tab2", you'll see name1 to name6. But rowData already has "name7". Just click on the filter-menu-icon and "name7" appears.

I hope, this helps.

**Comment by ceolter** [comment]
if you get the grid to refresh after the tab is show, that will fix it.

gridOptions.api.refreshView();

i don't know why ng2-bootstrap is interfering with it, i'm guessing it's stopping the grid from realising how much data it can render when first show. just guessing, i don't use ng2 or bootstrap myself in apps.
