### ISSUE TITLE
angular 2 type support?

### ISSUE THREAD

**Issue by fripp0971** [ceolter/ag-grid-ng2#2]
I can't figure out how to use this grid without a grid reference being passed to my angular 2 component class via an event.

For instance, I want to initially bind data that is coming from an http request, which is an observable. 

If I load up the grid with no data, and then create a button that passes a ref for the grid (#agGrid) to my button click, i can then set a component level grid variable that i can later use wherever i want.

Is there some way to reference the grid (and therefore its apis) through an angular 2 component? 

Perhaps this is a typescript issue?

**Comment by ceolter** [comment]
have you checked with the ng2 example i provide? that uses the api??

On 16 February 2016 at 21:17, fripp0971 <notifications@github.com> wrote:

> I can't figure out how to use this grid without a grid reference being
> passed to my angular 2 component class via an event.
>
> For instance, I want to initially bind data that is coming from an http
> request, which is an observable.
>
> If I load up the grid with no data, and then create a button that passes a
> ref for the grid (#agGrid) to my button click, i can then set a component
> level grid variable that i can later use wherever i want.
>
> Is there some way to reference the grid (and therefore its apis) through
> an angular 2 component?
>
> Perhaps this is a typescript issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2/issues/2>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by fripp0971** [comment]
Niall,

I think I did see that as I pretty much scoured your docs! Just in case do
you have a link? Also, does it use typescript entirely?

**Comment by ceolter** [comment]
yes it uses typescript

https://www.ag-grid.com/best-angular-2-data-grid/index.php

https://github.com/ceolter/ag-grid-ng2-example

On 16 February 2016 at 22:27, fripp0971 <notifications@github.com> wrote:

> Niall,
>
> I think I did see that as I pretty much scoured your docs! Just in case do
> you have a link? Also, does it use typescript entirely?
> On Feb 16, 2016 4:19 PM, "Niall Crosby" <notifications@github.com> wrote:
>
> > have you checked with the ng2 example i provide? that uses the api??
> >
> > On 16 February 2016 at 21:17, fripp0971 <notifications@github.com>
> wrote:
> >
> > > I can't figure out how to use this grid without a grid reference being
> > > passed to my angular 2 component class via an event.
> > >
> > > For instance, I want to initially bind data that is coming from an http
> > > request, which is an observable.
> > >
> > > If I load up the grid with no data, and then create a button that
> passes
> > a
> > > ref for the grid (#agGrid) to my button click, i can then set a
> component
> > > level grid variable that i can later use wherever i want.
> > >
> > > Is there some way to reference the grid (and therefore its apis)
> through
> > > an angular 2 component?
> > >
> > > Perhaps this is a typescript issue?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ceolter/ag-grid-ng2/issues/2>.
> > >
> >
> >
> >
> > --
> > --
> >
> > The information transmitted is intended only for the person or entity to
> > which it is addressed and may contain confidential and/or privileged
> > material. Statements and opinions expressed in this e-mail may not
> > represent those of the sender. Any review, retransmission, dissemination
> or
> > other use of, or taking of any action in reliance upon, this information
> by
> > persons or entities other than the intended recipient is prohibited. If
> you
> > received this in error, please contact the sender immediately and delete
> > the material from any computer.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ceolter/ag-grid-ng2/issues/2#issuecomment-184879214
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ceolter/ag-grid-ng2/issues/2#issuecomment-184900461>.
>



-- 
-- 

The information transmitted is intended only for the person or entity to
which it is addressed and may contain confidential and/or privileged
material. Statements and opinions expressed in this e-mail may not
represent those of the sender. Any review, retransmission, dissemination or
other use of, or taking of any action in reliance upon, this information by
persons or entities other than the intended recipient is prohibited. If you
received this in error, please contact the sender immediately and delete
the material from any computer.

**Comment by fripp0971** [comment]
Thanks so much!!

Question - does the grid support the rowsdata being an observable using an
async pipe behind the scenes? Or just an array?

Also, is there a way to access the grid from the component directly?

**Comment by fripp0971** [comment]
Never mind my question about the direct access. I see how you do it with
the empty gridoptions being passed in now.

I think this gives me what I was missing.

Thanks for being so quick and direct. Extremely impressed :)

Thanks

Chris

**Comment by ceolter** [comment]
```Question - does the grid support the rowsdata being an observable using an
async pipe behind the scenes? Or just an array?```
-> no, you have to pass the rowdata as an array

```Also, is there a way to access the grid from the component directly?```
-> i think this is the one you answered yourself
