### ISSUE TITLE
using bootstrap tooltips inside render function

### ISSUE THREAD

**Issue by drnknmstrr** [ceolter/ag-grid-ng2#22]
I'm trying to get bootstrap style tooltips to work inside my cellRenderer. If I return 

<a href="#" data-toggle="tooltip" title="Hooray!">Hover over me</a>

I get default tooltips instead of the nice bootstrap ones. I know you have to opt in first so I thought the problem was timing with the cellRenderer. I've put timeouts in that opt in for tool tips well after the grid is loaded:
(<any>$('[data-toggle="tooltip"]')).tooltip();

That makes all my other tooltips look fine, but not the ones inside the table. Any idea what I'm missing?

**Comment by pfvisser** [comment]
I got it working by re-initializing the tooltip after the grid data change and when the grid view port stop scrolling.

    private handleGridViewPortChangedOnScrolling(): void {
        let scrollTimeoutId: number;
        this.scrollSubscription = Observable.fromEvent(jQuery('.ag-body-viewport'), 'scroll').subscribe(() => {
            window.clearTimeout(scrollTimeoutId);
            scrollTimeoutId = window.setTimeout(() => {
                this.activateBootstrapTooltips();
            }, 250);
        });
    }

Note that I used JQuery to capture the scroll event.

**Comment by ceolter** [comment]
given a solution was given, and this is a bootstrap tooltips issue (ie nothing to be fixed in ag-Grid), i'm closing the issue.
