### ISSUE TITLE
no license file

### ISSUE THREAD

**Issue by laurelnaiad** [ceolter/ag-grid-ng2#23]
I had been assuming this was an MIT-licensed project, but I just noticed there's no license. Would you please put a file in the repo to declare any licenses you wish to grant? Thank you! :)

**Comment by ceolter** [comment]
done. it's MIT. same as ag-Grid. however ag-Grid-Enterprise is commercial. so you are free to use ag-grid-ng2 free of charge if you are only using it with ag-Grid. if you use it with ag-Grid-Enterprise, well you will need enterprise license for ag-Grid-Enterprise.
