### ISSUE TITLE
Viewport filtering: got empty FilterModel

### ISSUE THREAD

**Issue by Hafureluspatha** [ceolter/ag-grid-ng2#28]
Hello, ceolter. Today I've met strange behaviour and would be grateful if could help me.
My gridOptions(just in case):
```
enableSorting: true,
enableColResize: true,
viewportRowModelPageSize: 130,
viewportRowModelBufferSize: 200,
rowGroupPanelShow: 'always',
rowModelType: 'viewport'
```
In template I have `(filterChanged) = setFilterOption($event)`.
When I open filter menu, there's no options except `Select All` and an empty search field, but the data is showed. 
When I change selection, I and try to see event and filterModel 
```
console.log(event);
console.log(this.gridOptions.api.getFilterModel());
``` 
both event and filterModel are empty objects`Object{__proto__}`.
I get an empty object no matter if `Select All` is ticked or not. Nothing happens when I enter something in the search field and hit Enter. Filter model seems not to refresh with this move.
However, when I do this without implementing viewport (all rows are loaded and showed at once), `this.gridOptions.api.getFilterModel()` gives me an object with correct information:
```
Object { department: Array[2] }
```
Also other options besides `Select All` appear.
The questions are: How to get filterModel in viewport? Should I set it manually every time I do `setViewportRange`?

**Comment by ceolter** [comment]
I think you are using setFilter

setFilter will work with viewport, but the filtering has to be done server side.

setFilter cannot populate the list of available values as these are only available from the server, as the whole dataset is not loaded into the grid.

so you need to provide the values to the filter. this is done in the second example on this page:
https://www.ag-grid.com/javascript-grid-virtual-paging/index.php

the 'Select All' only selects all the values (checkboxs) in the filter. if no values, then it's useless.
