### ISSUE TITLE
routerLink is not working with cellRenderer call back

### ISSUE THREAD

**Issue by ssashok10** [ceolter/ag-grid-ng2#29]
I am using "AG-GRID-NG2" v5.2.3. Here is my columnDefs. If i use "href" on cellRenderer call back, it works fine. However, if I use, "routerLink", its is not working. I am using AngularJS RC 5 and Angular router RC 1. The "routeLink" on the anchor tag is working any where else in my application except on the "cellRenderer" call back.  

```
 columnDefs = [
        {
            headerName: "All", field: "All", width: 30, checkboxSelection: true
        },
        {
            headerName: "Id", field: "Id", width: 110, cellRenderer: function(params) {
                return '<a  routerLink="/search/'+params.value+'"/>'+params.value+'</a>';
            }
        },
];
```

**Comment by stephanjust** [comment]
routerLink is a AttributeDirective. You can not simply add an AttributeDirective into a random HTML tag and expect Angular to compile it in real-time.

https://www.ag-grid.com/best-angular-2-data-grid/index.php contains a tutorial on how to setup cell renderers for Angular 2.

**Comment by ssashok10** [comment]
Thanks. I tried the link which you mentioned. It works.

**Comment by ceolter** [comment]
@stephanjust Thanks Stephan :)

**Comment by ssashok10** [comment]
I recently migrated to the latest version of AG-GRID-NG2 and i noticed that "agComponentFactory" gives error on "routerLink" attribute. It was a working code with the older version of AG-GRID-NG2. I followed the new documentation and tried the below,

```
   {
            headerName: "Id", field: "Id", width: 110, cellRendererFramework: {
                    template: '<a routerLink="/search/{{params.value}}">{{params.value }}</a>' }
        },
```

I am getting the below error message,

```
node_modules/@angular/core/bundles/core.umd.js:3462 EXCEPTION: Template parse errors:
Can't bind to 'routerLink' since it isn't a known property of 'a'. ("<a [ERROR ->]routerLink="/search/{{params.value}}">{{params.value }}</a>"): DynamicComponent@0:3
```

This approach is suggested in the below link too,
https://github.com/ceolter/ag-grid-ng2/issues/49

However, its not working. Can you please let me know what is wrong with "cellRendererFramework"? Thanks.

**Comment by stephanjust** [comment]
```Can't bind to 'routerLink' since it isn't a known property ```
is an error message that appears when a declaration is missing, meaning routerLink is unknown to Angular 2. This can easily happen as with the newest versions of Angular and AgGrid you have to tell CellRenderers which modules to include. I assume this should fix it:
```
import { RouterModule } from '@angular/router';
{
  headerName: "Id", field: "Id", width: 110,
     cellRendererFramework: {
        template: '<a routerLink="/search/{{params.value}}">{{params.value }}</a>',
        moduleImports: [RouterModule]
    }
},
```

**Comment by ssashok10** [comment]
Awesome...Thanks Stephan. It works. it would be really nice if it is documented on the AG-GRID official page.

**Comment by stephanjust** [comment]
https://ag-grid.com/javascript-grid-cell-rendering/index.php
includes that information in the Angular 2 section, but I assume it would be really helpfull to have breaking changes like that in a seperate changelog as I stumpled across the same error.

**Comment by lterfloth** [comment]
Sorry for digging up this issue but I tried the code you provied @stephanjust and it gives me the error "No component factory found for [object Object]. Did you add it to @NgModule.entryComponents". I thought this was - more or less - an inline definition of a component? Did they change something? I've been looking for any information on it the last couple of days... Sorry for bothering!

**Comment by Roystine** [comment]
Hi, @ssashok10 can you please share an example of the code that you used to resolve this.
