### ISSUE TITLE
ComponentResolver has been deprecated in RC5

### ISSUE THREAD

**Issue by SaltyDH** [ceolter/ag-grid-ng2#31]
As per: https://github.com/angular/angular/blob/master/CHANGELOG.md (RC5 section)

> Instead of ComponentResolver:
> use ComponentFactoryResolver together with @NgModule.entryComponents or ANALYZE_FOR_ENTRY_COMPONENTS provider for dynamic component creation.
> use NgModuleFactoryLoader for lazy loading.

Just a heads up at this point, we're up on the daily builds (What will become RC6) of NG2 so this has been completely removed now rather than deprecated. The grids still work fine, I haven't investigated which functionality of the ag-grid specifically requires the ComponentResolver dependency.

**Comment by ceolter** [comment]
thanks for raising. will look into into it also on this end.

**Comment by deacix** [comment]
Hi,

please fix it as soon as possible because ag-grid-ng2 is not working on RC6 :(

**Comment by seanlandsman** [comment]
We have updated this to work with rc6 - we'll be releasing this shortly

**Comment by seanlandsman** [comment]
this has now been released - 5.3.2
