### ISSUE TITLE
ngc returns `Unexpected value 'AgGridModule' imported by the module 'AppModule'`

### ISSUE THREAD

**Issue by philbern** [ceolter/ag-grid-ng2#36]
when i try to compile my angular 2 app through @angular/compiler-cli ngc command, i get the error `Unexpected value 'AgGridModule' imported by the module 'AppModule'`

seems like the module resolver of the compiler is not able to resolve the AgGridModule but i can't figure out why

if i run my app bootstrapped with platformBrowserDynamic, the module gets resolved and the ag-grids are rendering fine

**Comment by seanlandsman** [comment]
We'll look at this once ng2 has been released (final version), but at a guess it might be down to the fact that we use the RuntimeCompiler in our module, and the compiler isn't deployed (afaik).

**Comment by philbern** [comment]
Final version is out!

Here's a post explaining what has to be done in order to fix this issue:

http://stackoverflow.com/a/39515266/6805453

In short, if i get this right, the module has to be compiled with `@angular/compiler-cli ngc` to generate a `metadata.json` file that has to be delivered with the compiled module.

**Comment by seanlandsman** [comment]
thanks for the link - we'll investigate this early next week

with regards to 2.0.0, 6.0.2 (released yesterday) of ag-grid-ng2 (and examples) supports 2.0.0

**Comment by seanlandsman** [comment]
An update on this - I'm still investigating but analysis so far leads me to believe that AoT compilation with our ng2 module may not be possible, given we rely on COMPILER_PROVIDERS, and this cannot be resolved and compilation time (more generally, the compiler cannot resolve items that can only be determined at runtime).

An issue regarding this has been raised in the last day or so: https://github.com/angular/angular/issues/11780

The outcome of that issue will probably determine (in the short term at least) if we can provide AoT support

**Comment by seanlandsman** [comment]
I've just release 6.1.1-beta - can you give it a go and see if it resolves your problem

To use it, import AgGridModule in your module (not AgGridModule.forRoot() - this will remain for non-aot/dynamic components)

In summary, there are two choices here - either:

- AOT and **no** dynamic/ng2 components
- dynamic/ng2 components and **no** AOT

It is unfortunately not possible to have both AOT and dynamic ng2 components due to restrictions around whats possible with the cli.

**Comment by philbern** [comment]
Ok i'll try to give it a shot this week

I'll let you know the outcome

Thanks

**Comment by joanllenas** [comment]
I made a very simple example work based on the [angular class starter](https://github.com/AngularClass/angular2-webpack-starter), which uses webpack and does AOT and tree shaking.

**Comment by seanlandsman** [comment]
Thanks for this - I'll be releasing 6.1.1 which will include two options - one for aot and one without

I'll take a look at your link as soon as possible!

**Comment by seanlandsman** [comment]
6.1.1 release - please see https://www.ag-grid.com/best-angular-2-data-grid/#aot for AOT usage

thanks

**Comment by joanllenas** [comment]
I've tried using 6.1.1 and it is crashing at run-time.
```Error: Uncaught (in promise): Error: Error in ./Home class Home - inline template:1:2 caused by: No provider for Ng2FrameworkFactory!```

I have created a [working repo](https://github.com/joanllenas/ag-grid-ng2-webpack2-aot-test) (with ag-grid-ng2 version 6.1.2-beta) so you can try it.
Just change to 6.1.1 and you'll see it.

```
git clone https://github.com/joanllenas/ag-grid-ng2-webpack2-aot-test.git
npm i
npm start
```

Cheers

**Comment by seanlandsman** [comment]
Please use 6.1.1 and please see the docs for usage - you need to specify either AgGridModule.withAotSupport() or AgGridModule.withNg2ComponentSupport()

I've updated your repo (locally of course) and it works fine from what I can see

**Comment by joanllenas** [comment]
Sorry, I totally missed that step.
Works like a charm now.

Thanks

**Comment by philbern** [comment]
I just updated my project to Angular 2.0.2 and ag-grid 6.2.1/ag-grid-ng2 6.2.0

I configured my AoT compilation and bundling with rollup but when i run with the result bundle i get this ag-grid error:
>Uncaught TypeError: Cannot read property 'GridOptionsWrapper' of undefined

The same error have been referenced in #68 so it may be related.

Its probably worth to mention that in my rollup process i run the rollup plugin commonjs (which will convert from commonjs to ES2015 module handling). That is needed because it seems rollup only supports ES2015. I am also running buble to convert the end result from ES2015 syntax to ES5.

Any clue on what's the problem there?

**Comment by dmarginian** [comment]
@philbern I am seeing the same issue with Gridoptionswrapper. Have you been able to get past it?

**Comment by seanlandsman** [comment]
I've been working on moving our ng2 support to include aot and dynamic components and have it working now. We'll be releasing it soon, but its worth noting that I'm using systemjs-builder for the rolling up, not rollup. 

If you're using rollup you should be able to run it through the commonjs plugin, which should convert it to es2015.

I'll update once I have a beta ready everyone

thanks

**Comment by estabij** [comment]
I am using AOT and rollup, basically following the Angular 2 cookbook on https://angular.io/docs/ts/latest/cookbook/aot-compiler.html.

In rollup-config.js I have
commonjs({
    include: [
        'node_modules/rxjs/**',
        'node_modules/ag-grid-ng2/**'
    ]}
}),
..

I do a
node_modules/.bin/ngc -p tsconfig-aot.json
followed by
node_modules/.bin/rollup -c rollup-config.js

In app.module.ts I have
import { AgGridModule } from 'ag-grid-ng2';
..
@NgModule({
    imports: [
        BrowserModule,
        AgGridModule.withAotSupport(),
        ..

I do not get any errors while compiling or treeshaking but when I run ag-grid I get a
ReferenceError: require is not defined
in the Chrome devTools console.

Btw. in JIT mode using
@NgModule({
    imports: [
        BrowserModule,
        AgGridModule.forRoot(),

ag-grid does work.
