### ISSUE TITLE
createCellRendererFromComponent: importing a module containing a component with a templateURL crashes

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid-ng2#37]
I cannot guarantee that this is an AgGrid issue as the error messages don't provide proper stack traces, but based on my tests it surely looks like.

The newest iteration of Angular2 cell renderers requires to import modules such as CommonModule via createCellRendererFromComponent (as Angular2 no longer does so implicitly). My CellRenderer uses several custom directives from a module.

```
cellRenderer: this.agComponentFactory.createCellRendererFromComponent(AngularCellRenderer, this._viewContainerRef, [], [SharedModule])
```

If any component declared in SharedModule uses a templateURL instead of an inline template I receive the following error:

```
Error: Uncaught (in promise): Error: No ResourceLoader implementation has been provided. Can't read the url "../../views/activitybar.html"
```

with a stack trace that only include zone calls.

I have no way to test SharedModule by itself without AgGrid, but no other component/module shows that behavior (and without including the module my CellRenderer throws errors as some directive annotations are missing) so I assume something really is missing here.

**Comment by seanlandsman** [comment]
Do you have a plunker you can share? Otherwise I'll take a look and see if I can reproduce it (and then fix!)

thanks

**Comment by stephanjust** [comment]
You guys seriously need a plunkr to start with :p

Anyway, I managed to reproduce it in a new plunkr.
http://plnkr.co/edit/O4cgOxirsrRU7ZGVyIDl?p=preview

This link will crash with
```
nhandled Promise rejection: No ResourceLoader implementation has been provided. Can't read the url "app/somedirective.template.html" ; Zone: angular ; Task: Promise.then ; Value: Error: No ResourceLoader implementation has been provided. Can't read the url "app/somedirective.template.html"(…) Error: No ResourceLoader implementation has been provided. Can't read the url "app/somedirective.template.html"
```
Going into app/app.component.ts and uncommenting the template/commenting the templateUrl fixes it.

**Comment by stephanjust** [comment]
Still happening with ag-grid-ng2@6.0.4, but it works fine in a plunker now. I'll see if I can find another cause for the issue :/

**Comment by seanlandsman** [comment]
The plunker request was really just because I'm...lazy ;-)

I took a look at this and unfortunately the fix won't be trivial for us - it down to us angular creates resource loaders and resolves paths internally - as we're creating components dynamically angular is having a hard time working out where the file(s) references are, so defaults to a "no resource loader".

We will pick this up again, but given other work items I'm afraid this will probably have to be a limitation in the short term

**Comment by seanlandsman** [comment]
Hi @stephanjust 

Please take a look at the new 7.x beta thats available - this supports using templateURLs in both AOT and JIT mode: https://www.ag-grid.com/angular-2-beta-release/

**Comment by stephanjust** [comment]
I really should remember to check my open issues from time to time. Our project currently bundles all html files by auto inlining them, so this issue was indirectly solved by itself. Nevertheless this beta seems to be huge - not having AoT was a real bummer and ag-grid was in fact the only thing stopping us  (and it's also great in case we decide that bundling all the HTML is too much bloat and a few requests more won't hurt). Thanks for your work.
