### ISSUE TITLE
Multiple grids declare multiple RuntimeComponentModules

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid-ng2#38]
I have multiple different grids that all use the Angular2 CellRenderer. The scenario in detail is a page with a grid that acts as an entry page and a routed page that contains tabs whereas each tab contains its own grid. Quickly navigating either between the pages via routing or changing tabs so that a different grid gets rendered results in:
```
Error: Uncaught (in promise): Error: Type AngularCellRenderer is part of the declarations of 2 modules: RuntimeComponentModule and RuntimeComponentModule!(…)
```
I'm not sure how you should fix this or what I can do to avoid this, but it seems that RuntimeComponentModule gets recreated and redeclares my CellRenderer while the old one is still valid.

**Comment by seanlandsman** [comment]
Hi

AgGridModule needs to be at the root level. Specifically, AgComponentFactory needs to be an app wide provider.

Try that and let me know if its still a problem

**Comment by stephanjust** [comment]
I assume the problem comes from me also importing the module at other places (and therefore providing it again) as it didn't work properly for me as a global module alone. I think fixing my importing issue could solve this issue with it, but if I may make a suggestion:

https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root
Angular has a mechanic to only add providers on the root level, namely with the forRoot() method. If your module stops providing AgComponentFactory within providers but uses forRoot() it should solve 'all' problems while still working properly.

**Comment by seanlandsman** [comment]
Hi

Yes, this is something we're hoping to move to this week, which as you say would remove the need (I hope) to have this being necessary

**Comment by seanlandsman** [comment]
Hi Stephen,

Release 6.0.1 (released today) should fix this - please see the updated docs for how to use ng2 in ag-grid, but the particular change for this problem is to include the agModule as follows  

        imports: [
            BrowserModule,
            AgGridModule.forRoot(),

Can you please update and try with the latest version.

I'll leave this issue open until you verify that it is indeed fixed

thanks

**Comment by stephanjust** [comment]
This looks really promissing. Sadly we're still running rc5 as the update to rc6 caused too much trouble and we had a deadline; therefore the update to rc7 (and ag-grid) has to wait. I'll get to it sometime next week and tell you how it worked out.

**Comment by seanlandsman** [comment]
Yeah, the release of rc6 caused us to have to re-write a lot of how we handled components in ag-grid.

The upgrade from rc6 to 2.0.0 has however been fairly painless

**Comment by stephanjust** [comment]
The update to Angular 2.0.0 was succesfull and the error is gone. Great work :)
