### ISSUE TITLE
Attempt to use a dehydrated detector: GridComponent_2 -> virtualRowRemoved

### ISSUE THREAD

**Issue by ghaiat** [ceolter/ag-grid-ng2#4]
Hello,
Whenever i m navigating away from a page containing an ag-grid, i get the following error, even so i m using the latest version.

Any idea on how to fix this ?

Cheers

````
Error: Attempt to use a dehydrated detector: GridComponent_2 -> virtualRowRemoved
    at DehydratedException.BaseException [as constructor] (exceptions.js:15)
    at new DehydratedException (exceptions.js:99)
    at AbstractChangeDetector.throwDehydratedError (abstract_change_detector.js:305)
    at AbstractChangeDetector.handleEvent (abstract_change_detector.js:53)
    at AbstractChangeDetector.eval (viewFactory_GridComponent:1344)
    at async.js:120
    at cb (ng_zone.js:402)
    at angular2-polyfills.js:1679
    at Zone.run (angular2-polyfills.js:1243)
    at Zone.run (ng_zone.js:344)
````

**Comment by ghaiat** [comment]
hello
any update about this ?

**Comment by ceolter** [comment]
nope. i won't be looking into it for the moment because investigating Angular 2 issues takes so much time.

**Comment by ghaiat** [comment]
the fix is quite easy:

Replace in the AgGridNg2 constructor:
```
ComponentUtil.EVENTS.forEach((eventName) => {
            (<any>this)[eventName] = new EventEmitter();
        });
```

By
```
ComponentUtil.EVENTS.forEach((eventName) => {
            (<any>this)[eventName] = new EventEmitter(false);
        });
```

This allows the use of synchronous emitter.

**Comment by ceolter** [comment]
if i put this change in, what are the implications?
wondering if i need to make it a property to allow client to decide

**Comment by ghaiat** [comment]
i dont think there are any. the issue was that you were emitting an asynchronous event when destroying the grid, so then angular was processing the event but the grid was already destroyed.

see below for full discussion on the topic:

https://github.com/angular/angular/issues/6786

**Comment by ceolter** [comment]
so maybe i just stop emitting events when the grid is destroyed?

**Comment by ghaiat** [comment]
not sure why you re emitting those events for. it s seems to be able to clean the virtual rows ..
if you don t think it  s necessary,not emitting would work as well, but i dont think there is any downside in using the fix i provided. it does fix the issue ...

**Comment by ceolter** [comment]
when i say i'll not emit the events, i mean i'll not emit them to angular, internally the events can still work for the grid to get them cleaned down

**Comment by ghaiat** [comment]
either solutions seems fine to me :)

**Comment by ceolter** [comment]
fix released. now it doesn't emit events if been destroyed. i think they didn't intend for me to emit events during the destroy phase, otherwise they would support  it!

**Comment by laurelnaiad** [comment]
awesome. Thank you @ceolter !
