### ISSUE TITLE
Pipes not working in createCellRendererFromTemplate()

### ISSUE THREAD

**Issue by rchipman** [ceolter/ag-grid-ng2#40]
Using the [example](https://github.com/ceolter/ag-grid-ng2-example) all I did was modify [from-template.component.ts line 25](https://github.com/ceolter/ag-grid-ng2-example/blob/master/app/from-template.component.ts#L25) to include a pipe:

```javascript
cellRenderer: this._agComponentFactory.createCellRendererFromTemplate('{{params.value * params.value | currency}}', this._viewContainerRef),
```

This causes an error to be thrown in the console and displays nothing for the cell in the grid:

```
core.umd.js:5995 EXCEPTION: Uncaught (in promise): Error: Template parse errors:
The pipe 'currency' could not be found ("[ERROR ->]{{params.value * params.value | currency}}"): Fake@0:0`
```

**Comment by seanlandsman** [comment]
Hi

We're in the process of working on our next major release (6.x) which will include support for pipes (by allowing you to supply dependant modules - in your case CommonModule).

We'll be doing the release tomorrow, so I'd recommend waiting for the 6.x release and check out the example again.

**Comment by rchipman** [comment]
Awesome thanks!

**Comment by seanlandsman** [comment]
Hi

6.0.1 has just been released - it includes support (with examples) of pipes.

thanks for reporting this
