### ISSUE TITLE
Update angular to final (non-rc) version

### ISSUE THREAD

**Issue by Brocco** [ceolter/ag-grid-ng2#41]
Based upon this comment: https://github.com/ceolter/ag-grid-ng2/pull/39#issuecomment-247293390 the update to RC7 has been completed, but now that the final version has been released (2.0.0) the version of angular should be updated.

**Comment by seanlandsman** [comment]
Aaargh! We literally just released 6.0.1 to support (amongst many other features) RC7

I'll look at this and update accordingly - thanks

**Comment by seanlandsman** [comment]
Release of 6.0.2 supports 2.0.0. - thanks

**Comment by Brocco** [comment]
@seanlandsman yeah rc7 and final came very close together, thanks for the releases!
