### ISSUE TITLE
grid keeps NgZone occupied / hangs e2e tests

### ISSUE THREAD

**Issue by laurelnaiad** [ceolter/ag-grid-ng2#43]
The app's NgZone .hasPendingMacrotasks is pinned at true while ag-grid-ng2 is on the page. This can happen if there is polling-like activity that prevents the zone from settling. Is it the globalEventListener? If so, one way to fix this may be to do the polling outside the angular zone. Right now, the pending macrotasks are making impossible to run protractor tests with a grid on the page. Eek! I hope I'm mistaken.

**Comment by seanlandsman** [comment]
Hi,

Thanks - we'll take a look at this. Does this apply for the latest version (6.0.2) too?

**Comment by laurelnaiad** [comment]
Yes.

1) up to a point recently, we were fine. No problems with:

* angular up to/including rc4
* ag-grid up to and including 4.2.0
* ag-grid-ng up to and including 4.2.0
* protractor up to and inclulding 3.1.1

One major round of updates later, and angular 2.0.0 and protractor 4.0.8, the following versions seem to exhibit this issue by git history inspection, so yes, this applies to latest.

```
    "ag-grid": "^5.2.0",
    "ag-grid-ng2": "^5.2.3",
```
and 
```
    "ag-grid": "^6.0.1",
    "ag-grid-ng2": "^6.0.2",
```

Thanks for looking into this! Most of our tests are hanging right now over this, so obviously I'm happy that you noticed my issue!

**Comment by laurelnaiad** [comment]
P.S. I had done this to myself in my own code, too. The solved code for the cases where I was hanging the NgZone with pending macrotasks looks like:

```
    this.zone.runOutsideAngular(() => {
      let tick = Observable.interval(10*1000).startWith(null)
      .map(() => this.zone.run(() => {
        this.store.dispatch(actions.search(key, {
            start: 0,
            length : 200,
            status: ['open'],
        }))
      }))
      this.pollSubs = tick.subscribe()
    })
```
... so obviously getting that interval out of the zone was the answer in my case.

**Comment by laurelnaiad** [comment]
I think one take away from the fact that I was just confronted with this issue in my own code and ag-grid is that something in the angular/protractor handshake has become more strict.

**Comment by laurelnaiad** [comment]
Here's a plunker of the problem: http://plnkr.co/edit/oFhi92DuxPnkiKhjhwZi?p=preview

**Comment by laurelnaiad** [comment]
I was going to say that it looks like whatever is keeping the zone occupied might be ticking at a 1/2 second rate, then I came across LAYOUT_INTERVAL=500 in ag-grid... https://github.com/ceolter/ag-grid/blob/97aaa34ace6f434d86e1a2d97f22a6e195604403/src/ts/constants.ts#L11 .

Seems to me quite likely the problem is in periodicallyDoLayout https://github.com/ceolter/ag-grid/blob/d60dec55225eb3da16a64dd829f8fb4c06ab46c8/src/ts/gridCore.ts#L199.

**Comment by laurelnaiad** [comment]
I can reduce that by setting layoutInterval to 0 but then the else clause's setTimeout kicks in and the tick goes to 5 seconds.

**Comment by laurelnaiad** [comment]
I have a patch for this. I will push it later tonight. I'm sure it's not what you all will ultimately keep, but at least it allows for e2e testing for now.

**Comment by seanlandsman** [comment]
hi @laurelnaiad - thanks for your hard work on this! We are hoping to look at this soon, and will roll any fix into the next release of ag-grid

**Comment by Garbett1** [comment]
This is a blocker on us using Ag-Grid at the moment, any timeline on when this might be released?

**Comment by seanlandsman** [comment]
hi @laurelnaiad @Garbett1 

I'll be looking at this today - will hopefully have a fix out for it soon

**Comment by seanlandsman** [comment]
Will be fixed in the next release - thanks for your investigation on this @laurelnaiad
