### ISSUE TITLE
Getting Error: No provider for Ng2FrameworkFactory! using 6.0.2 and angular 2.0.0

### ISSUE THREAD

**Issue by ricardogomes** [ceolter/ag-grid-ng2#44]
Hi

I just updated a project to angular 2.0.0 from the rc5. And also ag-grid-ng2 to 6.0.2.

The only change was moving the component directive declaration to the module declarations property.

Now I got this error:

core.umd.js:3462 EXCEPTION: Uncaught (in promise): Error: No provider for Ng2FrameworkFactory!

Am I missing something in the upgrade, or is this just something that still in the works?

Thanks

**Comment by seanlandsman** [comment]
Please see the documentation on https://www.ag-grid.com/best-angular-2-data-grid/index.php

You need to import the AgGridModule as follows:
```
@NgModule({
    imports: [
        BrowserModule,
        AgGridModule.forRoot(),
    ...
})
```

**Comment by ezzkht** [comment]
AgGridModule.forRoot() is deprecated. use AgGridModule.withComponents() instead.
