### ISSUE TITLE
getting property export is undefined

### ISSUE THREAD

**Issue by Ellipizle** [ceolter/ag-grid-ng2#45]
i tried to use ag-grid-ng2 using angular-cli [webpack] beta 12
i get this error "Export is  not defined" when i clicked it happens to show this link of code
`exports.AgGridModule = require('./lib/aggrid.module').AgGridModule;`

**Comment by seanlandsman** [comment]
Can you please retry with 6.1.1 and let me know if this is still a problem for you?
