### ISSUE TITLE
EXCEPTION: Uncaught (in promise): Error: Error in app/adjustor/adjustor.html:12:6 caused by: No provider for Ng2FrameworkFactory!

### ISSUE THREAD

**Issue by suncds** [ceolter/ag-grid-ng2#48]
I have listed in my package.json I am attempting to use   "ag-grid": "~6.0.1", "ag-grid-ng2": "~6.0.3"
with angular version 2.0.0  I am receiving the following run-time error: EXCEPTION: Uncaught (in promise): Error: Error in app/adjustor/adjustor.html:12:6 caused by: No provider for Ng2FrameworkFactory!
The adjustor.html file has the grid defined.  The grid was working as of ag-grid 5.4.0 and ag-grid-ng2 5.4.0 with angular 2.0.0rc6

**Comment by pfvisser** [comment]
Need to specify AgGridModule.forRoot() in your NgModule

`@NgModule({
    imports: [
        BrowserModule,
        AgGridModule.forRoot(),
    ...
})`

[Check the documentation here](https://ag-grid.com/best-angular-2-data-grid/index.php)

**Comment by seanlandsman** [comment]
@pfvisser yep, thats the solution

@suncds - please see https://www.ag-grid.com/best-angular-2-data-grid/index.php for details on how to configure ag-grid and ng2.

Its also worth noting that you should probably upgrade to 6.0.4 of ag-grid-ng2 as it fixes incorrect casing on main.d.ts
