### ISSUE TITLE
Does AG-Grid-NG2 support dynamic components?

### ISSUE THREAD

**Issue by rchipman** [ceolter/ag-grid-ng2#49]
Can we pass an instance of a component rather than the component class itself for cell and filter rending?  I ask because I have not found a way to create a generic type of link component that can accept parameters for where it link and what it should display.  Obviously this is a simple example, but the angular api supports creating components on the fly and accessing their instance properties and methods to supply outside data.

example, instead of doing this where I have to supply the link directly and utilize the params without any type safety:

```
import { Component } from '@angular/core';
import { AgRendererComponent } from 'ag-grid-ng2/main';

@Component({
    moduleId: module.id.replace("/dist/", "/src/"),
    selector: 'link-component',
    template: `
        <div>
            <a [routerLink]="['/dashboard']">{{params.value}}</a>
        </div>
    `
})
export class LinkComponent implements AgRendererComponent {
    private params: any;

    // called on init
    agInit(params: any): void {
        this.params = params;
    }
}
```

I'd like to be able to do something like this where the render method takes a function, creates a component and passes the function the to component on `agInit`:

```
@Injectable()
export class AgGridCellService {

    constructor(
        private componentFactoryResolver: ComponentFactoryResolver) { }

    render<T>(
        f: (model: T, params: any) => string,
        viewContainer: ViewContainerRef,
        dynamicComponent: { new (): DynamicAgGridCellComponent } = DynamicAgGridCellComponent): ComponentRef<DynamicAgGridCellComponent> {

        let factory = this.componentFactoryResolver.resolveComponentFactory(dynamicComponent);
        let ref = viewContainer.createComponent(factory);
        ref.instance.templateFunc = f;

        return ref;
    }
}
```
```
@Component({
    selector: 'dynamic-ag-grid-cell-component',
    template: '<div>{{template}}</div>'
})
export class DynamicAgGridCellComponent implements AgRendererComponent {
    private params: any;
    private template: string;

    @Input() templateFunc: Function;

    // called on init
    agInit(params: any): void {
        this.params = params;
        this.template = this.templateFunc(this.params.data, this.params);
    }
}
```
```
 columnDefs: any[] = [
        {
            field: 'operatingSystem',
            headerName: 'Operating System',
            cellRendererFramework: {
                  componentRef: this.cellService.render<LoginHistory>((lh) =>
                       `<a [routerLink]="/dashboard">${lh.operatingSystem}</a>`, this.viewContainer),
            }, 
            filter: 'text',
            filterParams: { apply: true, newRowsAction: 'keep' }
        }
    ];
```
I can supply further detail if this is confusing.

**Comment by stephanjust** [comment]
You're looking for the context, cellRendererParams and cellEditorParams objects.

Context is part of your gridOptions and therefore static for each grid instance. If you have multiple of them and want to set certain non-grid settings for your renderers/editors that's the place.
https://www.ag-grid.com/javascript-grid-context/index.php

cellRendererParams and cellEditorParams are passed to each renderer/editor in a certain column:
https://www.ag-grid.com/javascript-grid-cell-rendering/
https://www.ag-grid.com/javascript-grid-cell-editing/index.php
Settings them will simply expand the existing params object that you get in AgInit with your object.

Lastly you can add anything to a row itself. If there's data in the row that doesn't have a corresponding column in the grid nothing happens, but you have full access to the row inside your renderers/editors.

**Comment by seanlandsman** [comment]
What @stephanjust has said above is accurate, and is the preferred route.

For Filters you have the additional option of pulling the component instance via the api and invoking any method on the component - for example:

    api.getFilterInstance('name').getFrameworkComponentInstance().myMethod()

See https://www.ag-grid.com/javascript-grid-filtering/index.php for more details about this.

This isn't currently available for other component types (ie renderers and editors), but is something we'd like to add soon

**Comment by rchipman** [comment]
OK, so there is no option of passing a `ComponentRef` that implements `AgRendererComponent` where we can then initialize any properties or call methods using the ref before passing to the framework?

Do you think that Angular 2 provides a way to supply dynamic template html to a component that then gets compiled, similar to `$compile()` in angular 1 so that we can have a single generic `CellComponent` that will allow us to build custom cells without the need for adding lots of different concrete components?

I was able to accomplish this in Angular 1 with the grid and it made building out new grids much easier.

I can do this easily with just the standard `cellRenderer` function but the problem arises when needing to tie functionality back to the angular 2 app itself, like links or button clicks. 

Thanks for your quick responses!

**Comment by seanlandsman** [comment]
Not at this time no.

That said, you should be able to achieve what you want by using cellRendererParams and cellEditorParams - pass in the differing metadata via these mechanisms and use them in agInit.

I've not tried this but I cant see why this would work.

Its also worth noting that you can also specify renderers as just template strings - so in your particular example you could do this:

    cellRendererFramework: {
        template: `<a [routerLink]="/dashboard">${lh.operatingSystem}</a>`
    }

This only applies for renderers though

**Comment by rchipman** [comment]
@seanlandsman  I tried your suggestion and it seems to work fine.  Is there a way to access the params within the template property?  Perhaps a `templateFunction: (params): string => {}`?

**Comment by seanlandsman** [comment]
If you're asking about template renderers, then the params object is implicitly available - you can simply refer to it and it should work.

For eg, from one of our examples (ag-grid-ng2-example):

```
{{params.value * params.value}}
````

Is that what you mean?

**Comment by rchipman** [comment]
No, what i was asking about is making the `params` object available for the creation of components using the template property (or a new templateFunction method) for the angular 2 `cellRendererFramework`.

e.g.

```
colDefs: [
    field: 'exampleField',
    headerName: 'Example Field'
    cellRendererFramework: {
        templateFunction: (params) => `<a [routerLink]="[params.data.linkBase, params.data.linkId]">{{params.value}}</a>`,
        moduleImports: [RouterModule]
    }
]
```

Where the `templateFunction` would generate a component that will exist within the standard angular 2 scope, i.e. it will execute the directives present in the html.  Does that make more sense?

**Comment by seanlandsman** [comment]
To be clear - and its possible I'm still not following - but the params object is available to your template.

ie, 

```
colDefs: [
    field: 'exampleField',
    headerName: 'Example Field'
    cellRendererFramework: {
        template: `<a [routerLink]="[params.data.linkBase, params.data.linkId]">{{params.value}}</a>`,
        moduleImports: [RouterModule]
    }
]
```

would work, assuming linkBase etc are available on the params object. The params object is available to the template implicitly.

In other words, you should have all you need to create the components you're looking for.

**Comment by rchipman** [comment]
That is excellent news and works perfectly, I apologize for being slow to understand.  Thanks again for you quick responses!

**Comment by sebastian-zarzycki-es** [comment]
Is this usage of cellRendererFramework document anywhere? What is the scope/context of the template specified like this? For instance, can I call from it methods of the host component? (the component that has ag-grid in its html).
