### ISSUE TITLE
Cannot update angular to 2.0.1 because of exact peer dependency version

### ISSUE THREAD

**Issue by basvandenberg** [ceolter/ag-grid-ng2#50]
The peer dependencies @angular/core and @angular/compiler have exact versions: 

```
  "peerDependencies": {
    "@angular/core": "2.0.0",
    "@angular/compiler": "2.0.0",
    "ag-grid": "6.0.x"
  }
```

This prevents updating to the latest angular patch update 2.0.1. Could this peer dependency version be changed to 2.0.x (or ~2.0.0) to enable installing angular patch updates without having to wait for an ag-grid-ng2 update?

**Comment by seanlandsman** [comment]
Hi

We'll be doing a new release later this week, and I'll include this change as part of that - thanks for raising this.

**Comment by AloeDream** [comment]
@seanlandsman  Angular 2.1.0 is already in beta, so please count that too.

**Comment by seanlandsman** [comment]
Thanks - I'll take a look at the beta too. We'll probably be less open to supporting _any_ minor/beta release given the breaking changes in the release candidates it may be that we allow any patch version and selected minor/beta versions.
 
Thanks for raising this!

**Comment by AloeDream** [comment]
@seanlandsman , I don't ask to support beta, but I ask to support any minor version, otherwise, many people who use angular-cli may have to wait for your new builds to be able to update CLI. And CLI updates are pretty important and many developers would like to install new versions ASAP.

**Comment by seanlandsman** [comment]
ok, thats fair then - I'll include that too

**Comment by seanlandsman** [comment]
latest release supports any minor version
