### ISSUE TITLE
Not able to access "this" from cellRendererFramework

### ISSUE THREAD

**Issue by ssashok10** [ceolter/ag-grid-ng2#52]
I am using cellRendererFramework to generate a URL on a cell like the below,

```
cellRendererFramework: {
                template: '<a routerLink="/search/{{params.value}}">{{params.value }}</a>',
                moduleImports: [RouterModule]
            }
```

Now i need to generate different template URLs based on the value on the Angular Component. I tried to use "this" to access component variables inside "cellRendererFramework" and it is not working.

**Comment by seanlandsman** [comment]
You cant access the component when using templates - you'll need to implement the cellRenderer using an actual component.

Checkout the docs for examples on how to do this
