### ISSUE TITLE
AgGrid cellRendererFramework template works only on first load

### ISSUE THREAD

**Issue by rchipman** [ceolter/ag-grid-ng2#53]
The first time that the grid is displayed it works fine, but if I navigate away and then come back to the grid's route, the grid crashes and throws an error.  If I then refresh the page it loads the grid fine, but will always fail after I navigate away from the grid and return.

Here is the template code:

```
     {
            field: 'operatingSystem',
            headerName: 'Operating System',
            cellRendererFramework: this.link("['/dashboard']", "{{params.data.operatingSystem}}"),
            filter: 'text',
            filterParams: { apply: true, newRowsAction: 'keep' }
     }

     link(routerLinkParams: string, linkText: string) {
        return {
            template: `<a [routerLink]="${routerLinkParams}">${linkText}</a>`,
            moduleImports: [RouterModule]
        }
    }
```

and here is the error:

```
TypeError: Cannot read property 'create' of null
    at ViewContainerRef_.createComponent (core.umd.js:5307)
    at AgComponentFactory.createComponent (agComponentFactory.js:169)
    at CellRenderer.createComponent (agComponentFactory.js:80)
    at CellRenderer.BaseGuiComponent.init (agComponentFactory.js:222)
    at CellRenderer.init (agComponentFactory.js:67)
    at CellRendererService.useCellRenderer (cellRendererService.js:47)
    at RenderedCell.useCellRenderer (renderedCell.js:936)
    at RenderedCell.putDataIntoCell (renderedCell.js:885)
    at RenderedCell.populateCell (renderedCell.js:682)
    at RenderedCell.init (renderedCell.js:287)
```

Any ideas?

**Comment by seanlandsman** [comment]
Hi,

Thanks for raising this - I'll investigate this as soon as possible, but realistically will only get to this on Monday now.

Can you give a little more context around this please? When you say navigate away, are you doing so via a route for example?  Or another site altogether (seems unlikely though!)?

thanks

**Comment by rchipman** [comment]
Yes sorry, I plan on making a plunkr for this issue but I have not had the time, perhaps I can work on it today or at the very least get you something for Monday.  What I meant by navigate away is navigating around the SPA using Angular 2's provided router. 

For example, I had an AgGrid on my user's profile page to show their login history.  The first time the user views the profile page they see this:

<img width="836" alt="screen shot 2016-09-28 at 9 07 48 am" src="https://cloud.githubusercontent.com/assets/3871032/18914448/2b101faa-855b-11e6-832e-5aa760815a80.png">

After navigating away to one of the other pages of the site and returning to their profile page they see this and they get the error detailed above in their console: 

<img width="832" alt="screen shot 2016-09-28 at 9 09 47 am" src="https://cloud.githubusercontent.com/assets/3871032/18914500/668e036c-855b-11e6-8a13-f057ec919d3f.png">

It looks like the grid is attempting to render all the cells but when it gets to the first cell that used the `cellRendererFramework` it hangs and cannot recover and so never paints the rest of the grid,

**Comment by seanlandsman** [comment]
Sounds like it could well be a timing issue - perhaps the component hasn't fully been created/resolved in time?  Rhetorical question :-)

**Comment by rchipman** [comment]
Yea, I think you are probably correct about the timing issue.  

I had another quick question, I have a local storage service that stores the current state of the grid including the page that the user was on.  The data works fine but I can't figure out how to set the current page of the grid upon refresh.  Meaning that the data represents what would be the third page of the grid, but the grid is displaying that it is the first page of the grid.  

That said, when I page up or down it jumps to the correct page (if it was on page 3 of the data and click next it jumps to page 4).  Is there a way to set the current page of the grid on load?

**Comment by seanlandsman** [comment]
For this sort of thing (ie non issues) can we please move it to the free forum: https://ag-grid.com/forum/forumdisplay.php?fid=4 

For now though, are you using simple pagination here? And you've then gone to page 3, saved the state, reloaded and restored the state?

**Comment by rchipman** [comment]
Yes, page to page three, reload.  The local storage will re run the filter which includes odata params for $top and $skip which represents the third page of data.  Then I need to set the current page of the grid to show it as being on page 3.  Accomplishing this right now by manually changing the html and setting the current page on the `pagincationController` as indicated above.  I was looking for something like `paginationController.setPage(currentPage)` that would handle the grid internals (and allow for custom pagination in the future).

**Comment by seanlandsman** [comment]
The particular functionality you're looking for (goto page etc) is definitely in the pipeline (and soon), but isnt something we offer yet I'm afraid.

You're not the first to ask for it though, so we know theres definitely a need for it - I'll bump it further up the priority list.

Re gitter, we do have a channel there which I watch daily too: https://gitter.im/ceolter/ag-grid, so you could post either there or the free forum above :-)

**Comment by smperng** [comment]
I hit this issue too. It seems to arise from ag-grid interaction with angular 2 router.

I can easily repro this if I add a couple of routes to ag-grid-example and make both routes show the  <ag-from-template></ag-from-template>. The first time both routes will work, but not afterwards.

**Comment by seanlandsman** [comment]
I've released ag-grid-ng2@6.1.2-beta to fix this - can you give it a go and let me know if it resolved the issue? 

I was able to reproduce this fairly easily and found the problem, but I want to ensure theres not some use case I've missed here

**Comment by rchipman** [comment]
It appears to be fixed for my current case! Aweosme.

**Comment by seanlandsman** [comment]
@rchipman 6.1.1 has been released - this is the "official" non-beta release, and includes this fix

thanks
