### ISSUE TITLE
do typings need to be required? 

### ISSUE THREAD

**Issue by squarewave24** [ceolter/ag-grid-ng2#56]
it appears that typings are required, and this introduces a problem when building with --production flag. typings are only a devDependency. 

do they need to be required? or shouldn't it be up to whomever is developing to decide. 

> npm ERR! ag-grid-ng2@6.0.4 postinstall: `typings install`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the ag-grid-ng2@6.0.4 postinstall script 'typings install'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
>

**Comment by squarewave24** [comment]
one way to get around this issue was to install typings globally.

**Comment by seanlandsman** [comment]
In the latest release typings has been removed - if you upgrade to 6.1.0 this problem will go away
