### ISSUE TITLE
ng2 component name failing when web pack with uglify

### ISSUE THREAD

**Issue by benharrell** [ceolter/ag-grid-ng2#57]
the first renderer works but all others do not do the way you build the map.

i think you need 

(<any>type).constructor.name

instead of 

(<any>type).name

agComponentFactory lines 58,82,94

testing further but pretty sure this is the issue....

**Comment by benharrell** [comment]
sorry this might be caused by web pack, researching more

**Comment by benharrell** [comment]
this is probably uglify mangling the type name which is then used later in your map of renderers...trying this now

webpack.optimize.UglifyJsPlugin({mangle: false}).

**Comment by benharrell** [comment]
another option:

new webpack.optimize.UglifyJsPlugin({
        mangle: {
            keep_fnames: true
        }
    }),

**Comment by benharrell** [comment]
UPDATE:  removed optimize--minimize for web pack and the problem went away.

more info here - https://github.com/webpack/docs/wiki/optimization

**Comment by vigie** [comment]
Just wanted to note this will also be an issue for anyone using uglify-js outside of web pack. It can be solved  using the --keep-fnames option, here is an example of setting that using gulp-uglify:

`.pipe(uglify({mangle: { keep_fnames: true} }))`
