### ISSUE TITLE
Worked perfectly with angular RC 4 but not working with angular 2.x

### ISSUE THREAD

**Issue by naveen2911** [ceolter/ag-grid-ng2#58]
I used ag-grid-ng2 with angular RC-4 version it was working perfectly fine but after upgrade to 2.x its not working correctly. It seems when applied pagination using rowModelType = "pagniation" data does not load.

**Comment by seanlandsman** [comment]
do you have a plunker we can look at? that side of things should not have changed between versions

**Comment by ceolter** [comment]
should be no difference here. the pagination is part of the core grid, nothing changed with this between ng2 updates.

**Comment by ssashok10** [comment]
pagination works fine for me with Angular 2 except one scenario with cellRendererFramework and i posted it here.....

https://github.com/ceolter/ag-grid-ng2/issues/60

**Comment by seanlandsman** [comment]
#60 can serve as the issue for this - we dont need both
