### ISSUE TITLE
Unable to override styles

### ISSUE THREAD

**Issue by gaminoff** [ceolter/ag-grid-ng2#62]
I'm trying to customize the grid by overriding css classes in the scss file of the grids hosting component.
Can I even do that? or only by adding another global css file (with overriding styles) to index.html?

**Comment by seanlandsman** [comment]
You should be able to customise styling within a given component/cell, but to override the grid as a whole you'll need to override the styles at the same "level" as the ag-grid css. So in your case it would probably have to be done in index.html as you say

**Comment by ceolter** [comment]
question answered, so closing. plenty of examples in the docs of changing the themes and styles.
