### ISSUE TITLE
Installation requires that Typings be installed

### ISSUE THREAD

**Issue by pierreUMAknow** [ceolter/ag-grid-ng2#63]
When Typings is not installed, the npm install ag-grid-ng2 command fails with an error "postinstall 'typings install'". Doing npm i -g typings solves the issue. At the very least, it should be indicated in the documentation. With Typescript 2, I believe this should now be unneccessary.

**Comment by seanlandsman** [comment]
Typings is no longer part of the install - upgrade to the latest and it is no longer necessary

thanks
