### ISSUE TITLE
Context Menu in Angular2 project

### ISSUE THREAD

**Issue by nunna-suma** [ceolter/ag-grid-ng2#67]
I'm trying to implement the context-menu in my angular2 project. so , that whenever right-click on rowitem it has to show the menu with copy,alert like these options. I tried to place the syntax and functionality in coding but no use it is not working and there is no errors also.

can anyone please help me to slove these issue 
Thanks in advance.

**Comment by seanlandsman** [comment]
Are you using the enterprise version of ag-grid?

**Comment by nunna-suma** [comment]
No ,i'm not using enterprise version

**Comment by seanlandsman** [comment]
the context menu functionality is only available in the enterprise version of ag-grid - please take a look at the ag-grid documentation for more details, especially on whats available in the free vs the enterprise versions of ag-grid
