### ISSUE TITLE
Problem after I update to beta 12

### ISSUE THREAD

**Issue by pantonis** [ceolter/ag-grid-ng2#7]
Hi,

This is my systemjs

`System.config({
            packages: {
                app: {
                    format: 'register',
                    defaultExtension: 'js'
                },
                'ag-grid-ng2': {
                    defaultExtension: "js"
                },
                'ag-grid': {
                    defaultExtension: "js"
                }
                ,
                map: {
                    'ag-grid-ng2': 'app/grid/ag-grid-ng2',
                    'ag-grid': 'app/grid/ag-grid'
                }
            },
        });
        System.import('app/boot')
              .then(null, console.error.bind(console));`

and Im getting following error

Error: Error: XHR error (404 Not Found) loading http://localhost:1228/ag-grid-ng2/main.js(…)ZoneDelegate.invoke @ angular2-polyfills.js:332

**Comment by arturalkaim** [comment]
Hi,

I'm facing the same error.

How did you solved this issue?

Thanks
