### ISSUE TITLE
Scroll to top on page change.

### ISSUE THREAD

**Issue by Overload94** [ceolter/ag-grid-ng2#70]
**Feature request**: The grid should scroll first row into view when the page is changed in pagination row model type.

**Comment by seanlandsman** [comment]
Hi - thanks for the request. Can you please file it under https://github.com/ceolter/ag-grid instead - this is reserved for ag-grid-ng2 specific issues if possible

I'm happy to do it though, so if I dont hear back by next week I'll close this issue and create a new on in the ag-grid repo

**Comment by Overload94** [comment]
Hi Seanlandsman, thanks for the suggestion. Will file it under ag-grid.
