### ISSUE TITLE
[Feature Request] Grid height based on rows

### ISSUE THREAD

**Issue by stephanjust** [ceolter/ag-grid-ng2#71]
As Niall mentions [here](https://www.ag-grid.com/forum/showthread.php?tid=4266&pid=10578#pid10578):

>  are you expecting the grid height to adjust with the number of rows? if yes, this is not a feature we support (if it worked in a previous version of ag-Grid, this was by accident).

This accident was in fact the case. The grid was capable of growing based on its row count and it was great. Several versions ago this stopped working and we didn't bother as we're still in some sort of prototype stage, but currently it would help a lot (for a single page application that uses only the browser scroll bar, e.g all components should be stretched to full height).

This is half possible alread by setting ```forPrint``` in ```gridOptions```. Sadly due to the lack of vertical scrolling the grid crashes upon tabbing, as some elements are not available in this mode that the grid requires. I assume it's really only for printing.

Any chances this might be added again?

**Comment by seanlandsman** [comment]
Hi - thanks for the request. Can you please file it under https://github.com/ceolter/ag-grid instead - this is reserved for ag-grid-ng2 specific issues if possible

I'm happy to do it though, so if I dont hear back by next week I'll close this issue and create a new on in the ag-grid repo
