### ISSUE TITLE
templateUrl for cellRenderers from Angular 2 components

### ISSUE THREAD

**Issue by Nim-C** [ceolter/ag-grid-ng2#72]
Hi,

I have followed the tutorial for Cell Rendering (https://www.ag-grid.com/javascript-grid-cell-rendering/index.php) and the ag-grid-ng2-example (https://github.com/ceolter/ag-grid-ng2-example) and I didn't notice cellRenderers using Angular 2 Component's templateUrl.

Does the option for Angular 2 component's templateUrl exists?

Thanks in advance

**Comment by seanlandsman** [comment]
Hi,

Not at this time I'm afraid - when creating components dynamically the path is hard for the ng2 runtime to determine. 

I'm hoping to look at this in the next few weeks and can update this thread once I have an update if that helps

**Comment by Nim-C** [comment]
This would definitely help since it's preferred to keep complex templates in separated files.

Thanks

**Comment by seanlandsman** [comment]
hi @Nim-C 

Please take a look at the new 7.x beta thats available - this supports both AOT and JIT mode: https://www.ag-grid.com/angular-2-beta-release/, and supports templateURLs in both AOT and JIT mode

**Comment by Nim-C** [comment]
Hi @seanlandsman 

Tried it and it works great!
Thanks a lot :+1: 

Nim-C
