### ISSUE TITLE
Header Component (headerRendererFramework?)

### ISSUE THREAD

**Issue by petterfreak** [ceolter/ag-grid-ng2#73]
Hi,

We would like to buy this awesome grid for our angular2 app... But first, we would like to know, does any option for declare header as ng2 component instead of headerCellRenderer/headerCellTemplate? 

We read/tried that, there is an option for cells, but what about headers?
`
....
cellRendererFramework: {
    component: anyComponent
}
.....
`

**Comment by seanlandsman** [comment]
Hi,

Unfortunately as you've discovered this functionality is not yet available - it is on the roadmap and is something we're looking to do in the next few weeks.

I can update this issue however when this is ready if that helps though!

thanks,

**Comment by petterfreak** [comment]
Hello,

I would like to ask about when this feature will be released? Or can you mention a workaround? We want to place interactive charts, texts, images in the header and communicate with the angular2 parent component.

Thank you

**Comment by seanlandsman** [comment]
hi @petterfreak - its on the list for this year. We have a backlog and its #3 on the list, so should be available in the new few weeks.

In the meantime you can try use the current header rendering options (https://www.ag-grid.com/javascript-grid-header-rendering/) but as I say it shouldn't be too long before you'll be able use ng2 components for this instead

**Comment by norbidroid3d** [comment]
I can hardly wait this new feature, custom grid header would be a great improvement, coz header rendering is very painful currently.

**Comment by Renaud009** [comment]
This would be an amazing feature for us too. We are wondering if it's gonna be possible to import ng2 modules too juste like in cellRendererFramework? 

Translating the grid cells with ng2-translate was a breeze to use with the cellRendererFramework as we only have to use the translate pipe instead of instant() which needs to be re-called after some events (language change, asyn key receptions, etc.)

**Comment by albertosramires** [comment]
@seanlandsman Any updates on this?

**Comment by SylvestreMassalaz** [comment]
Hello, do you have any update on this?

**Comment by seanlandsman** [comment]
Hi - this has now been implemented in version 8x, released last week

thanks

**Comment by Renaud009** [comment]
I can't find any documentation how to use it?! Can anybody help me?

**Comment by AnaSofiaGrilo96** [comment]
Where can we find the documentation to use it this new feature? Any help, please?
