### ISSUE TITLE
Export to CSV for virtual rowModelType

### ISSUE THREAD

**Issue by nitoloz** [ceolter/ag-grid-ng2#74]
Hi!

I am using `rowModelType: 'virtual'` in my project and want to export the data to CSV using exportDataAsCsv() api function. However when I try to perform the export I get the following error in my browser console:
`csvCreator.js:53 ag-Grid: getDataAsCsv is only available for standard row model`

Could you please provide any workarounds or point out what I am doing wrong?

Best regards,
Andrey

**Comment by seanlandsman** [comment]
Hi,

You'll need to iterate over the data yourself when not using the standard row model, build up an array of arrays and expose that yourself.

You can iterate the the gridOptions.api.forEachNode methods here

Please note - can you please raise issues not related to ng2 specifically in the https://github.com/ceolter/ag-grid repo instead please - thanks!
