### ISSUE TITLE
AOT or angular2 components 

### ISSUE THREAD

**Issue by feloy** [ceolter/ag-grid-ng2#76]
I can read in the doc that we have to choose between AOT support or angular2 components in the grid.

Is this definitive (by concept), or is there a chance that the problem is resolved in the future?

**Comment by seanlandsman** [comment]
Hi @feloy - we're working on something at the moment which should allow both AOT and ng2 components in the grid. Current eta is around 2-3 weeks - sooner hopefully with a beta

**Comment by feloy** [comment]
Great, thanks!

**Comment by seanlandsman** [comment]
I've been working on moving our ng2 support to include aot and dynamic components and have it working now. We'll be releasing it soon - I'll update once I have a beta ready for everyone

thanks

**Comment by kashban** [comment]
That's great news! Looking forward to it.

**Comment by seanlandsman** [comment]
hi @feloy @kashban 

Please take a look at the new 7.x beta thats available - this supports both AOT and JIT mode: https://www.ag-grid.com/angular-2-beta-release/

**Comment by actimeo** [comment]
Hi Sean, thanks for this beta release. 

I had some trouble, having to use AgGridModule on different (lazy loaded) modules:

* First try: 
In each sub-module:
- I add in imports : AgGridModule.withComponents([MyComponent])
- I add in declarations: MyComponent

result: angular2 doesn't want I add MyComponent on each module "declarations", I have to put it in the top module.

* Second try:
- I add imports AgGridModule.withComponents([MyComponent]) in each module
- I add MyComponent in top module "declarations"

result: Angular2: "Component MyComponent is not part of any NgModule or the module has not been imported into your module."

* Third try: 
- I add imports AgGridModule.withComponents([MyComponent])  in top module
- I add MyComponent in top module "declarations"
- I "export" AgGridModule from my top module 
- I import AgGridModule from my sub-modules

results: That seems to work...
 
It would be interesting to document this use case. I can work on a simple demo git repo if you need.

**Comment by actimeo** [comment]
I would like to integrate this beta release in my CI build, but I would need an NPM package for this. Do you have the possiblity to provide such an NPM package for this beta release?

(actimeo === feloy, sorry for the confusion)

**Comment by seanlandsman** [comment]
Hi @actimeo 

For entryComponents I'm afraid it does have to go into the top level module, as you've discovered.

This is great feedback - this is the sort of thing I'm hoping for, use cases that our users will come across that we've not documented - thanks!

With regards to an npm package, it has been released as a beta - try ag-grid-ng2@7.0.0-beta.1

**Comment by petrosus** [comment]
Hi,
excellent work. I had the same issue as @actimeo - it's not working as separate angular feature module which is then imported by other modules. Components have to go in top level module.

Also had an issue with core.js taypings reference during build - if you remove reference from agGridColumn.d.ts everything is fine.

Thanks

**Comment by seanlandsman** [comment]
thanks @petrosus - can you please provide a bit more information around the typings issue?

**Comment by petrosus** [comment]
OK - I have just pulled new beta .4 version and run angular-cli build process and result is
_The error is ERROR in [default] ...\node_modules\ag-grid-ng2\lib\agGridColumn.d.ts:1:0 
Cannot find type definition file for 'core-js'_.
If I put @types/core-js as dev-dependecies then I have issue with duplicate identifier all around.
There is an article about this http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/

So I simply remove a reference `/// <reference types="core-js" />` from agGridColumn.d.ts and everything works fine.

**Comment by seanlandsman** [comment]
thanks @petrosus - I'll take a look and apply any changes  need

thanks for the feedback

**Comment by seanlandsman** [comment]
@petrosus 7.0.1 should fix this issue for you

@feloy @actimeo 7.0.0 includes these changes - have fun!

**Comment by kashban** [comment]
Great to see... though I have another module not AOT ready and as such cannot test it right now.
