### ISSUE TITLE
Interact with Output params in  cellRendererFramework

### ISSUE THREAD

**Issue by spinettaro** [ceolter/ag-grid-ng2#78]
Hi, 
I have a component to manage a column of ag-grid by cellRendererFramework feature. 
The component that I created have a child component that Emit Event. How can I manage the output params in cellRendererFramework feature?
The code below helps:
```
@Component({
  selector: 'ag-render-component',
  template: '<span>Hello component</span>',
  styleUrls: [],
  providers: []
})
export class MyRenderComponent implements AgRendererComponent {
@Output()
  onMyEvent = new EventEmitter();

agInit(params: any): void {
    this.params = params;
  }
}
```

How can I bind to onMyEvent?

**Comment by seanlandsman** [comment]
Take a look at the [clickable component](https://github.com/ceolter/ag-grid-ng2-example/blob/master/app/clickable.component.ts) in our examples repo for an example on how to do this

**Comment by spinettaro** [comment]
Yes, I see the example but I think it's not my case. What about if the @Output params is in clickable.parent.component.ts (https://github.com/ceolter/ag-grid-ng2-example/blob/master/app/clickable.parent.component.ts) ? And not in clickable.component.ts (https://github.com/ceolter/ag-grid-ng2-example/blob/master/app/clickable.component.ts) as the example suggests

**Comment by seanlandsman** [comment]
Where would you want the event to go in the case of clickable.parent.component?

**Comment by spinettaro** [comment]
The component represented in colDef (I think directly in ag-grid component):
```
cellRendererFramework: {
    component: MyRenderComponent
}
```
How can I bind to onMyEvent? You can see the code in my previous posts.

**Comment by spinettaro** [comment]
I think should be reopened... @seanlandsman any news about?

**Comment by GeorgeKnap** [comment]
Hi, I've run into this problem too. I think it's a common case to have a component where you create gridOptions containing colDef which has a Angular2 cellRendererFramework component. Inside that component's template is let's say simple `<a (click)=onclicked()>Click Me</a>` . And the only thing we want is to inform the parent component containing gridOptions that this particular  anchor tag was clicked.

**Comment by TheILPlace** [comment]
i've had to use a service, and inject it into the renderer companent. the outer component subscribes to an event the service emits.

**Comment by seanlandsman** [comment]
@spinettaro @GeorgeKnap @TheILPlace 

Having given it some thought I can now provide the following option to you:

You can use gridOptions.context for this - for an example take a look at:

Parent Component: https://github.com/ceolter/ag-grid-ng2-example/blob/master/systemjs_aot/app/from-component.component.ts

Child Component: https://github.com/ceolter/ag-grid-ng2-example/blob/master/systemjs_aot/app/child-message.component.ts

**Comment by Rosscotini** [comment]
Hi the above links produce 404 errors. Would love to see a working example of this

**Comment by kvloover** [comment]
Is there no other way to have a button fire an event that can be used in the parent component ?
It feels very weird that I have to know which functions my parent component has to implement in order to handle something.
