### ISSUE TITLE
Infinite loop if ag-grid used with angular2.0.0-beta.15.

### ISSUE THREAD

**Issue by swarke** [ceolter/ag-grid-ng2#8]
We are using ag-grid with angularjs-webpack-starter project. It is using angular2.0.0-beta.15.
When we  are adding directives in component section, it goes into infinite loop and we have to kill browser. 

@Component({
  selector: 'ag-grid',
  directives: [AgGridNg2],
  template: '<ag-grid-ng2 #agGrid style="width: 100%; height: 350px;" class="ag-fresh"
             [gridOptions]="gridOptions"
             [columnDefs]="columnDefs"
             [showToolPanel]="showToolPanel"
             [rowData]="rowData"
             enableColResize
             enableSorting
             enableFilter
             groupHeaders
             suppressRowClickSelection
             toolPanelSuppressGroups
             toolPanelSuppressValues
             debug
             rowHeight="22"
             rowSelection="multiple">
          </ag-grid-ng2> '
}

**Comment by DChau10** [comment]
If the above component is supposed to be your own, it doesn't make sense that you're overriding the selector for ag-grid.

```typescript
@Component({
  selector: my-component',
  directives: [AgGridNg2],
  template: `
    <ag-grid-ng2 *ngIf="gridOptions" #agGrid class="ag-fresh [gridOptions]="gridOptions"></ag-grid-ng2>
    `
}
export class MyComponent {
  private gridOptions: GridOptions;
  constructor () {
    //do stuff...(i.e. update gridOptions)
  }
}
```

**Comment by seanlandsman** [comment]
Agree with @DChau10 - don't override the selector. Please see the examples provided in ag-grid-ng2-examples
