### ISSUE TITLE
Grid update when data source is updated

### ISSUE THREAD

**Issue by Nim-C** [ceolter/ag-grid-ng2#82]
Hi,

According to @ceolter ,binding is not yet supported
(https://github.com/ceolter/ag-grid/issues/953#issuecomment-225171627)

My data source is an array which is consistently updating (Employees: Employee[]).
Every time I update the array, I use "GridOptions.api.setRowData(Employees)" in order to update the grid.

Now, when I use the row grouping, and an Employee's field is updated, after the "setRowData", the group's order is changed, and it is quite disturbing.

Is there a better way to update the grid (according to the data source) instead of overriding the rowData?
(Generally. not only for the groups issue)

Thanks in advance
Nim-C

**Comment by ceolter** [comment]
i assume you are doing pagination? you can also use datasource in viewport and infinate scrolling, so not sure which you are talking about.

either way, the grid doesn't sort the data without you asking, so if you pass the data in in the same order, it will result in the same groups. so pass the data in in the same other. otherwise apply a sort to the grid after you pass in the data.

you could also just update the row that you are updating, rather than setting the whole data into the grid again.

**Comment by Nim-C** [comment]
An example:
`var Employees = [
	{
		Name: A,
		MaritalStatus: 'Single'
	},
	{
		Name: B,
		MaritalStatus: 'Single'
	}
	];`

From my understanding it seems like you suggest managing the data in both the data source and the grid.

My purpose is to manage the data only in the array, and make the grid update through the API.

For the example above We'll have a grid with two columns (Name, Marital Status), and two rows for each of the employees.
My purpose is making the grid update once I am make a change in the data source (Employees array).

> you could also just update the row that you are updating, rather than setting the whole data into the grid again.
I tried to update the row using `GridOptions.api.forEachNode`(to find the node represents the row), and updated  the "RowNode.data"  of the node, and also used `GridOptions.api.refreshRows([updatedNode]);`(to refresh the row) but it Didn't work.

How can I update a specific row?
If I will add/remove employees to the example array, what should I do to make the grid update according to the changes I made in the example array?

**Comment by ceolter** [comment]
use rowNode.setDataValue(colKey, newValue)

explained here: https://www.ag-grid.com/javascript-grid-refresh/

**Comment by STRRL** [comment]
use template and ng-bind like this
[{headerName:"Name",template:'<span ng-bind="data.Name"></span>'}]

**Comment by STRRL** [comment]
sorry i forget decode
[{headerName:"Name",template:'&lt;span ng-bind="data.Name"&gt;&lt;/span&gt;'}]
