### ISSUE TITLE
is it reponsive?

### ISSUE THREAD

**Issue by kodiraj** [ceolter/ag-grid-ng2#85]
hi,

Is the ag-grid-ng2 reponsive? or we need to hanlde it ourself in mobile devices

**Comment by seanlandsman** [comment]
Hi

The grid will fill a container (ie a div) that you give it, so if the div expands/contracts it will grow/shrink with it.

In addition there is the capability to show/hide columns, tool panels etc programatically when appropriate, but you would need to handle this yourself.

Going forward please post support enquiries in the forum: ag-grid.com/forum/

thanks
