### ISSUE TITLE
v7.0.0 missing core-js definition file

### ISSUE THREAD

**Issue by samalexander** [ceolter/ag-grid-ng2#87]
When using ag-grid-ng2 version 7.0.0, we are seeing the following error:
`Cannot find type definition file for 'core-js'`

We have tried installing the core-js typescript definitions as a workaround, but this does not resolve the issue.

**Comment by scic** [comment]
I have the same problem. It happens in the file agGridColumn since it's referencing core-js with
/// <reference types="core-js" />

Error:
node_modules/ag-grid-ng2/lib/agGridColumn.d.ts:1:0 
Cannot find type definition file for 'core-js'.

**Comment by dylabar** [comment]
I can confirm removing the line that @scic mentions does get rid of webpack compilation errors. However, I then run into issues at run time. In particular, I receive the following error:

`No provider for Ng2FrameworkFactory!`

**Comment by seanlandsman** [comment]
I'll take a look at the core-js issue today

@dylabar With regards tot he no provider issue, can you please supply your module definition?

**Comment by seanlandsman** [comment]
7.0.1 released to fix the typing issue - let me know if its still a problem for you 

thanks

**Comment by samalexander** [comment]
Thanks @seanlandsman. This fixes the issue for me.
