### ISSUE TITLE
Pagination problem

### ISSUE THREAD

**Issue by gieboyz** [ceolter/ag-grid-ng2#88]
Hi i have some problem when i trying to implement pagination after the data i get using http.
the data not showing when in the first load, but the data will show after button next, can you help me to fixed it.

> private gridOptions:GridOptions;
	private columnDefs:any[];
	private rowOfficesData:any[] = [];
	private temp:any[];
	offices: Office[];
	constructor(
		private officeServices: OfficeServices,
	){
		//this.getOffice();
		this.gridOptions = <GridOptions>{};
		this.gridOptions.columnDefs = this.createColumnDefs();
		this.gridOptions.enableFilter= true;
		this.gridOptions.rowData = this.offices;
		this.gridOptions.rowModelType = "pagination";
		this.gridOptions.datasource = {
			rowCount : -1,
			paginationPageSize: 1,
			overflowSize: 10,
			getRows: (params: any) => {
				var rowsThisPage = this.offices.slice(params.startRow, params.endRow);
				var lastRow = -1;
				params.successCallback(rowsThisPage, lastRow);
			}
		};
	}
	ngOnInit(){
		this.getOffice();
	}
	getOffice() {
		let _self = this;
		this.officeServices
		.getOffice().subscribe((offices:Office[])=>{
			_self.offices = offices;
		});
	}

the results is.

![example1](https://cloud.githubusercontent.com/assets/9793593/20790507/3a16e93a-b7eb-11e6-9e3d-4e1502c660e5.png)

after i click button next
![example2](https://cloud.githubusercontent.com/assets/9793593/20790536/5e011b36-b7eb-11e6-852d-2ab757627058.png)

and also show error log in console.log
![example3](https://cloud.githubusercontent.com/assets/9793593/20790667/f3bb5f74-b7eb-11e6-9f22-77032b7de78a.png)

**Comment by seanlandsman** [comment]
This is almost certainly due to the grid being ready and call datasource.getRows **before** this.officeServices.getOffice() returns.

You'll need to alter your code to set the datasource when the getOffice call is done
