### ISSUE TITLE
ag-Grid: count not find matching row model for rowModelType normal

### ISSUE THREAD

**Issue by nkagarw** [ceolter/ag-grid-ng2#89]
After upgrading the ag-grid version in my Angular2 app from 6.4.0 to 7.0.1 and changing from `AgGridModule.withNg2ComponentSupport()` to `AgGridModule.withComponents([])` in my app.module.ts,

I'm getting this error on a page where I have an ag-grid instance that is using the forEachNodeAfterFilter method :

> cannot call forEachNodeAfterFilter unless using normal row model

I don't have any rowModelType set in the ag-grid assuming it uses the normal (inMemoryModel) by default. If I manually set the rowModelType to 'normal' in the gridOptions, I get the following error : 

> ag-Grid: count not find matching row model for rowModelType normal

Everything works perfectly when I switch back to v6.4.0. But, I want to upgrade to the newer version to take advantage of better Angular2 support.

**Comment by nkagarw** [comment]
Some more info on the error : while trying to debug grid.js, I notice that Grid.RowModelClasses['normal'] returns undefined (please see the attached screenshot)

![debugger](https://cloud.githubusercontent.com/assets/12206754/20863064/0ee2c94a-b97c-11e6-87bb-700081a6ec4a.png)

**Comment by ceolter** [comment]
i don't know what's wrong, however can you try setting property rowModelType='normal'

**Comment by nkagarw** [comment]
That's the 2nd point i've mentioned, if I set the property rowModelType='normal', I get 

> ag-Grid: count not find matching row model for rowModelType normal

**Comment by nkagarw** [comment]
It's still the same error whether I set rowModelType = 'normal' manually using gridOptions or through an attribute in the grid html declaration.

> ag-Grid: count not find matching row model for rowModelType normal

**Comment by seanlandsman** [comment]
Hi @nkagarw - do you have a plunker or similar we can investigate? We can try work out why you're seeing the error you're seeing

**Comment by ceolter** [comment]
can you also post the code where you are configuring ag-grid?

**Comment by ceolter** [comment]
can you confirm, both ag-grid, ag-grid-ng2 and ag-grid-enterprise (if using) are all on 7.0.x, that you have updated versions on all?

**Comment by nkagarw** [comment]
Hi @seanlandsman, it's difficult to create an angular2/typescript plunker. Is there a sample angular2 plunker available with boilerplate code ? I'll add my code there and try to reproduce the error.

@ceolter, yes, i'm using the latest version of both. Here are the lines from package.json and the page where aggrid is instantiated :

**package.json**
```
    "ag-grid": "^7.0.2",
    "ag-grid-ng2": "^7.0.1",
```


**picker.component.html**
```
                <ag-grid-ng2 #es style="width: 100%; height: 300px;" class="ag-material"
                             [gridOptions]="gridOptions"
                             [columnDefs]="colDefs"
                             [rowData]="list"
                             (gridReady)="gridReady($event)"
                             (rowSelected)="gridRowSelected($event)"
                             (rowDoubleClicked)="gridRowDoubleClicked($event)"
                             (modelUpdated)="modelUpdated($event, search)">
                </ag-grid-ng2>
```


**picker.component.ts**
```
    constructor(private service: AppService, public dialog: DialogRef<PickerData>) {
        this.colDefs = [
                { headerName: "Id", field: "SpecimenId" },
                { headerName: "Name", field: "Name" },
                { headerName: "Unit Of Measure", field: "UnitOfMeasure" }
        ];

        this.gridOptions = {
            columnDefs: this.colDefs,
            rowHeight: 40,
            rowModelType : 'normal',
            rowSelection: 'single'
        }

        this.service.getData(this.url, this.parms, false)
         .subscribe(d => this.list = d,  err => console.log("Error" + err) );
    }

    modelUpdated(event, search) {
        search.focus();
        if (event.fromIndex && event.fromIndex.type == "columnEverythingChanged")
            return;

        //Select the first visible row everytime
        this.gridOptions.api.forEachNodeAfterFilter(function (node, index) { if (index == 0) node.setSelected(true) });
    }
```

**Comment by seanlandsman** [comment]
Hi,

Here is plunker you can use as a basis for your example: http://plnkr.co/edit/J04rdB?p=preview

Looking at your code I don't see anything obviously wrong or that should cause a problem. 

Can you please try use the plunker example provided and see if you can reproduce the problem that way?

thanks

**Comment by nkagarw** [comment]
Thanks @seanlandsman.

Here is an updated plunker showing the same issue : http://plnkr.co/edit/uQ4DxNFEMBPV7nW1vCQs?p=preview

The only changes I made to your original plunker is removed the square, cube, params components and replaced the from-component with my picker component.

**Comment by seanlandsman** [comment]
Ok, a couple of things here

- there appears to be a bug where if you specify rowModelType : 'normal' the grid complains. This should not be the case and will be fixed. Just remove that line for now as it will default to normal
- the problems you're seeing are down to timing - modelUpdated is being called before the grid has been initialised

Try this:

`
modelUpdated(event, search) {
   if(!this.ready) return;
       
   search.focus();
   if (event.fromIndex && event.fromIndex.type == "columnEverythingChanged")
      return;

   //Select the first visible row everytime
   this.gridOptions.api.forEachNodeAfterFilter(function (node, index) { 
      if (index == 0) node.setSelected(true) });
   }

gridReady(event) {
   this.ready = true;

   // this.context isnt defined
   // this.text = this.context.value;
   // this.filterGrid(this.context.value);
}
`

**Comment by nkagarw** [comment]
Its working well with your suggestions. Thanks @seanlandsman.

**Comment by ktcith** [comment]
@ceolter Hi I'm facing the similar issue on my end. 
in my cases, I'm facing issues for infinite, not normal.

```
ag-Grid: count not find matching row model for rowModelType infinite
```

I've followed the tutorial but still getting the issue? 
Do you know what might cause this error?

Thanks.
