### ISSUE TITLE
No provider for Ng2FrameworkFactory

### ISSUE THREAD

**Issue by Lucasvo1** [ceolter/ag-grid-ng2#90]
Hi,

We are running into the following error: "No provider for Ng2FrameworkFactory". I am using this in combination with the ng2-admin dashboard. 

This is my **module.ts**

@NgModule({
  imports: [
    CommonModule,
    routing,
    NgaModule,
    FormsModule,
    AgGridModule
  ],
  declarations: [
    InstanceManager
  ],
  providers: [
    InstanceManagerDataService
  ]
})

And this is my **component** file

@Component({
  selector: 'instancemgr',
  styles: [require('./instancemanager.scss')],
  template: require('./instancemanager.html')
})

export class InstanceManager implements OnInit{

  data: Array<any>;
  private gridOptions: GridOptions = {};

  constructor(private _instanceManaagerDataService: InstanceManagerDataService) {
    this.data = _instanceManaagerDataService.data;
  }

  ngOnInit() {
    this.gridOptions.rowData = this.data();
    this.gridOptions.columnDefs = this.createColumnDefs();
  }

  private createColumnDefs() {
    return [
      { headerName: "Name", field: "name", width: 100},
      { headerName: "Server", field: "server", width: 100},
      { headerName: "Server IP", field: "serverip", width: 100}
    ]
  }
}

**Comment by seanlandsman** [comment]
Please refer to the documentation on how to use ag-Grid with ng2: https://www.ag-grid.com/best-angular-2-data-grid/

You need to import 

AgGridModule.withComponents(
        [..optional components...]
)

**Comment by ssashok10** [comment]
How should we define the "AgGridModule" when there is no optional components? If we use "AgGridModule" without "withComponents" option, i am getting the error ". No provider for Ng2FrameworkFactory" as mentioned above in this thread. When we use the below definition, i am getting the error "EXCEPTION: No component factory found for [object Object]".

`AgGridModule.withComponents([])`

What is the right way to define "AgGidModule" when there is no optional components involved?

**Comment by seanlandsman** [comment]
Just supple it as an empty array as you've done above:

```AgGridModule.withComponents([])

If you're getting an error with this then you have a different problem

**Comment by ssashok10** [comment]
Found the issue after reading the below blog,

https://www.ag-grid.com/ag-grid-angular2-support-v7/

I am using the "cellRendererFramework" with inline html string and the "moduleImport" statement and its no longer supported in "Ag-Grid" V7.  It works well in V6.x.x.

 cellRendererFramework: {
                template: '<a routerLink="/details/{{params.value}}">{{params.value }}</a>',
                moduleImports: [RouterModule]
}

I am changing the inline code to the component as below. Can you please let me know how to do the "moduleImport" on the cell renderer component level?

```
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
    template: '<a routerLink="/details/{{params.value}}">{{params.value }}</a>',
   //  moduleImports: [RouterModule]

})
export class CellRendererComponent { }
```

**Comment by ssashok10** [comment]
I made it work now. Here is my cell renderer component now,

```
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';
import { AgRendererComponent } from 'ag-grid-ng2/main';

@Component({
    template: '<a routerLink="/details/{{params.value}}">{{params.value }}</a>'

})
export class CellRendererComponent implements AgRendererComponent {
    params: any;
    agInit(params: any): void {
        this.params = params;
      }
}

```

**Comment by malford121** [comment]
This worked for me:

import {Component, OnDestroy} from '@angular/core';
import { ICellRendererAngularComp } from 'ag-grid-angular/main';

@Component({
    selector: 'cell',
    template: '<a routerLink="/details/{{params.value}}">{{params.value }}</a>'
})
export class CellRendererComponent implements ICellRendererAngularComp, OnDestroy {
    private params: any;

    agInit(params: any): void {
        this.params = params;
    }

    ngOnDestroy() {
        console.log(`Destroying SquareComponent`);
    }

    refresh(): boolean {
        return false;
    }
}
