### ISSUE TITLE
Ag Grid CSS not working in Webpack

### ISSUE THREAD

**Issue by sskmail14** [ceolter/ag-grid-ng2#91]
Ag Grid CSS not working
**_Output_**
![image](https://cloud.githubusercontent.com/assets/5357908/21001835/9b22ef8c-bd48-11e6-8b0a-1c90b4228ec9.png)

_**package.json**_
```
"ag-grid": "6.2.x",
"ag-grid-ng2": "7.0.x"
```
_**index.html**_
```
   <link href="/node_modules/ag-grid/dist/styles/ag-grid.css" rel="stylesheet"/>
    <link href="/node_modules/ag-grid/dist/styles/theme-fresh.css" rel="stylesheet"/>
```
**_app.module.ts_**
```
import {AgGridModule} from 'ag-grid-ng2/main';
import {SquareComponent} from './_custom_component/_AgGridModules/ag-grid-components';
.
.
.
@NgModule({
  declarations: [
.
.
.
.
,SquareComponent],
 imports: [.
.
.
,AgGridModule.withComponents([SquareComponent]),
.
.
]
})
```
**_test.component.ts_**
```
import { GridOptions } from 'ag-grid/main';
.
.
@Component({
  templateUrl: './test.component.html',
  styles:['.toolbar button {margin: 2px; padding: 0px;}'],
})
export class TestComponent {
  private gridOptions: GridOptions;
  public showGrid: boolean;
  public rowData: any[];
  private columnDefs: any[];
  public rowCount: string;

  constructor(private formBuilder: FormBuilder, http: Http, private route: ActivatedRoute, private router: Router) {
    this.gridOptions = <GridOptions>{};
    this.setCoulmnDefs();
  }

  // here we use one generic event to handle all the column type events.
  // the method just prints the event name
  private onColumnEvent($event) {
    console.log('onColumnEvent: ' + $event);
  }

  setCoulmnDefs() {
    this.rowData = [
      {name:"sample",age:78},
      {name:"Arun",age:22},
      {name:"sample",age:78},
      {name:"Arun",age:22},
      {name:"sample",age:78},
      {name:"Arun",age:22}
      ];
      console.log(this.rowData);
//commented code ends
   /* this.columnDefs = [
    
    {
      headerName: 'Name',
      suppressSorting: true,
      suppressMenu: true, 
      pinned: true,
      field:"name"
    },
     {
      headerName: 'Age',
      suppressSorting: true,
      suppressMenu: true, 
      pinned: true,
      field:"age"
    }
    
    ];*/
//commented code ends
  }
}
```
**_test.component.html_**
```
 <div class="col-sm-12" align="left">

    <ag-grid-ng2 #agGrid style="width: 100%; height: 90%;" class="ag-fresh" 
    [gridOptions]="gridOptions" [columnDefs]="columnDefs"
      [rowData]="rowData" enableColResize enableSorting enableFilter groupHeaders suppressRowClickSelection toolPanelSuppressGroups
      toolPanelSuppressValues debug rowHeight="22" rowSelection="multiple" (columnEverythingChanged)="onColumnEvent($event)"
      (columnRowGroupChanged)="onColumnEvent($event)" (columnValueChanged)="onColumnEvent($event)" (columnMoved)="onColumnEvent($event)"
      (columnVisible)="onColumnEvent($event)" (columnGroupOpened)="onColumnEvent($event)" (columnResized)="onColumnEvent($event)"
      (columnPinnedCountChanged)="onColumnEvent($event)">
 <ag-grid-column headerName="Name" field="name" [width]="150" [pinned]="true"></ag-grid-column>
      <ag-grid-column headerName="Age" field="age" [width]="150" [pinned]="true"></ag-grid-column>
    </ag-grid-ng2>
  </div>
```

Am missing something could some one have an idea on this?

**Comment by ceolter** [comment]
verify that this is working:
```
   <link href="/node_modules/ag-grid/dist/styles/ag-grid.css" rel="stylesheet"/>
   <link href="/node_modules/ag-grid/dist/styles/theme-fresh.css" rel="stylesheet"/>
```

see if the css files are getting loaded into your browser. it looks like they are not.

if they are not, then this is to do with whatever web browser, packaging system that you are using.

**Comment by seanlandsman** [comment]
Although not the cause of your issue, you should always keep the major (and preferably minor) versions of the ag components in line (ie use ag-grid 7.x too).

**Comment by sskmail14** [comment]
Still not working...

I have copies the css from ng-modules to my app css directory as those cant be servered from ng-modules directory.

The css is now getting served from server @ceolter as it was not served earlier.

![image](https://cloud.githubusercontent.com/assets/5357908/21005910/c487a494-bd5c-11e6-9031-4398ff85a4ee.png)

Changes as per @seanlandsman said
### package.json
![image](https://cloud.githubusercontent.com/assets/5357908/21005804/51d6bde0-bd5c-11e6-9d67-88d150bf4804.png)

Still the grid looks the same :(

![image](https://cloud.githubusercontent.com/assets/5357908/21005980/008ffce8-bd5d-11e6-8d62-601ef129456e.png)

**Comment by seanlandsman** [comment]
I think at this staged we'd probably require something we can look at - do you have a plunker or stripped down repo we can look at?

**Comment by sskmail14** [comment]
It works up for me!!!, I have referred [ag-gird-ng2 example](https://github.com/ceolter/ag-grid-ng2-example)

Thanks for your valuable time!!! @ceolter and @seanlandsman

**Comment by seanlandsman** [comment]
hey @sskmail14 - that's great! I am working on a webpack example now, but am glad you got it to work. What was the problem in the end?

**Comment by sskmail14** [comment]
@seanlandsman 
I removed all the code that I have implemented regarding ag-grid, I have followed the code that is in ng2 example. So exactly I was not able to place where the problem is.

I will repeat my steps that I have followed earlier(which doesn't work) later as am little hurry in development part and let you know where the exact problem is ASAP.

Thanks @seanlandsman

**Comment by tlann** [comment]
I had the same issue.  I was just copying the seed code from the repo.  I didn't realize there was a reference page on using the angular cli to build it.  Come to find out according to the [reference](https://www.ag-grid.com/ag-grid-angular-angularcli/#gsc.tab=0)  
The styles have to be added to  .angular-cli.json
"styles": [
"../node_modules/ag-grid/dist/styles/ag-grid.css",
"../node_modules/ag-grid/dist/styles/theme-fresh.css"
],


This issue also duplicated [here](https://github.com/ceolter/ag-grid/issues/1076)

**Comment by ian-moore** [comment]
@tlann thanks for commenting this. I was trying to recreate the bare-minimum configuration by hand and didn't see the style bundling called out in any of the angular examples.

**Comment by LiamDotPro** [comment]
Within the angular CLI guide it will tell you:

```
// .angular-cli.json
"styles": [
    "../node_modules/ag-grid/dist/styles/ag-grid.css",
    "../node_modules/ag-grid/dist/styles/theme-fresh.css"
],
```

With the latest ag-grid theme fresh is actually ` "../node_modules/ag-grid/dist/styles/ag-theme-fresh.css"` If you wondering why styling is not appearing.

**Comment by seanlandsman** [comment]
the only "legacy" styles are still there - ag-theme-fresh is a new style.

In other words the above docs should still apply and work as expected

**Comment by petyosi** [comment]
Sorry for that. The guide has a typo - `theme-fresh` should be either `ag-fresh` or `ag-theme-fresh`. We will fix this in the next docs update.

**Comment by sumant86** [comment]
I did import below css & it worked for me.

> @import url('../node_modules/ag-grid/dist/styles/ag-grid.css');
> @import url('../node_modules/ag-grid/dist/styles/ag-theme-fresh.css');

**Comment by upardhi** [comment]
Hi 

I tried 3 diffrent way but still I am not able to use the css 

First: 
@import "~ag-grid-community/dist/styles/ag-grid.css";
@import "~ag-grid-community/dist/styles/ag-theme-balham.css";

Second: 
Put all content available in above file in my component 

Third: 
@import url('../node_modules/ag-grid/dist/styles/ag-grid.css');
@import url('../node_modules/ag-grid/dist/styles/ag-theme-fresh.css');


Still css is not working

**Comment by shivamkhanna189** [comment]
@import "~ag-grid-community/dist/styles/ag-grid.scss";
@import "~ag-grid-community/dist/styles/ag-theme-balham.scss";

In place of .css use .scss it will work fine .
