### ISSUE TITLE
using ngIf with new dynamic  AgRendererComponent

### ISSUE THREAD

**Issue by ascalonwa** [ceolter/ag-grid-ng2#92]
When I have a component setup as follows:

```
@Component({
  selector: 'address-cell',
  template: `
<div *ngIf="row.addr1">{{row.addr1}}<br/></div>
<div *ngIf="row.addr2">{{row.addr2}}<br/></div>
`
})
```

I get the following error:
`Unhandled Promise rejection: Template parse errors:
Can't bind to 'ngIf' since it isn't a known property of 'div'. ("
<div [ERROR ->]*ngIf="row.addr1">{{row.addr1}}<br/></div>
<div *ngIf="row.addr2">{{row.addr2}}<br/></div>
"): AddressCellComponent@1:5
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "directives" section. ("
[ERROR ->]<div *ngIf="row.addr1">{{row.addr1}}<br/></div>
<div *ngIf="row.addr2">{{row.addr2}}<br/></div>
"): AddressCellComponent@1:0`

**Comment by seanlandsman** [comment]
Remember that angular 2 is case sensitive, so make sure to use ngIf, not ngif

**Comment by ascalonwa** [comment]
I understand that it is case sensitive, but it is ignoring the directive, or I get the above error.  I have tried different syntax.
`<div ngIf="row.addr1 === null">none</div>
<div *ngIf="row.addr1 === null">none</div>
`

They either get ignored or throws a syntax error.  
I know that this works normally in angular2 because I have created some controls using embeddedviews and the syntax works with straight angular 2.  I noticed in the older syntax, there was an "importModule" something like that where you could the component use additional imports, does that still exists, it seems that might be the problem.

**Comment by seanlandsman** [comment]
ok, it was worth mentioning

You'll need to ensure that dependant modules (in this case either BrowserModule or CommonModule) are imported in your module. This replaces the need for you to do so in the xxxxFramework properties.

**Comment by ascalonwa** [comment]
ok, I see what I did.  I create the grid in a separate module and my component was in another module, that didn't have all of the imports.  thanks!!
