### ISSUE TITLE
ng build -prod breaks cellRendererFramework

### ISSUE THREAD

**Issue by bialad** [ceolter/ag-grid-ng2#93]
I'm using ag-grid-ng2 7.0.1, and the cellRendererFramework functionality, in a angular-cli 1.0.0-beta.22-1 compiled application.

When compiling using `ng build` or `ng build --aot` everything works fine, however when compiling using `ng build -prod` (which to my knowledge adds minification and three shaking, could be more) the components created by ag-grid all always the same across grids.

Whichever components in the grid that is loaded first are the one that shows up in every grid.

The columnDefinitions are correct between grids. So if I use a component on both grids, but with different definitions it gets the correct params loaded in agInit() and works. It's just when the components are different in each grid it causes errors.

These are two grids columnDefinitions:
```
[
  { headerName: 'Field1', field: 'field1' },
  { headerName: 'Field2', field: 'field2' },
  { headerName: 'Field3', field: 'field3' },
  { field: '', endpoint: 'apt', cellRendererFramework: AptOptionComponent }
]
```
and
```
[
  { headerName: 'Field1', field: 'field1' },
  { headerName: 'Field2', field: 'field2' },
  { field: '', endpoint: 'owner', cellRendererFramework: OwnerOptionComponent }
]
```

This is the `agInit()` for each component
```
  agInit(params: any): void {
    this.endpoint = params.colDef.endpoint; // Get the correct respective value
  }
```

Looking in chrome devTools when first loading a grid with `AptOptionComponent`, and then `OwnerOptionComponent`, the correct component is named in `FunctionLocation`
![image](https://cloud.githubusercontent.com/assets/16528731/21073332/61a6e72e-bedb-11e6-9035-141992c183de.png)

But `apt-option` is the one that is actually loaded.

I've been trying to figure this out for a while now, and can't get my head around it. Anyone got any ideas, or maybe even a solution?

**Comment by seanlandsman** [comment]
Are you saying that if you have two grids with different column definitions, and separate components, that the two grids end up displaying only one of the components?

It would be really helpful if you could supply a stripped down plunker for me to look at and investigate, but in the meantime I'll see if I can reproduce this too

**Comment by bialad** [comment]
Yes, the component(s) in the first created grid gets used in all grids created after that. If I refresh the application to start on an other grid, those components get used in the following grids.

I'll try to get something together tonight, it's really hard to debug since it only occurs when the code is minified. I've been thinking about whether the minification gets confused, and sets the same function name to both component factories?

**Comment by bialad** [comment]
I had to create a repository on github for this. Clone it, and run `npm i` and `ng serve -prod` and you should see that the same components gets created in both grids.

https://github.com/bialad/ag-grid-ng2-test

**Comment by seanlandsman** [comment]
Hi @bialad - thanks for taking the time to reproduce this. The good news is I can reproduce it and think I see what the problem is. Its not directly in our code but I think I may have a solution to this - I'll try it out and update this issue

thanks

**Comment by seanlandsman** [comment]
Fixed - this will be available in our next release, currently scheduled for Wednesday next week

Thanks for reporting this

**Comment by bialad** [comment]
Awesome! Since this stops me from creating production builds, can I just make this change to my local library?

**Comment by seanlandsman** [comment]
Absolutely, go ahead!
