### ISSUE TITLE
Columns are not updated when using markup column definitions

### ISSUE THREAD

**Issue by AngularPadawan** [ceolter/ag-grid-ng2#94]
Hi,

given a grid set up using markup column definitions and *ngFor

<ag-grid-ng2 ...>
    <ag-grid-column *ngFor="let col of columns_typeA" [headerName]="col.headerName" [field]="col.field"></ag-grid-column>
    <ag-grid-column *ngFor="let col of columns_typeB" [headerName]="col.headerName" [field]="col.field"></ag-grid-column></ag-grid-ng2>

when columns_typeA or columns_typeB are changed then the columns in the data table are not updated. When the columsn are defined using the columnDefs Input parameter, the columns are updated properly. 

Is this somehow on purpose? In my case, I would rather use the markup column definitions since I have several different column types and am using *ngFor on the different sources (see example above). I can workaround the issue by using the columnDefs Input field, but would appreciate a solution anyway.

Thanks!

**Comment by seanlandsman** [comment]
Hi

Yes, at this stage the design was for a static/one off setup of the grid. What you're doing is perfectly reasonable and is something I can add to the backlog for us to look at, but as it stands what its doing is as expected (its what we were asked for by users that requested it - a one of declarative approach).

I'll update the docs to reflect this though - thank you for raising it.

**Comment by AngularPadawan** [comment]
Thanks for the reply and explanation! This is fine for me - will just continue to use my workaround.

**Comment by Wykks** [comment]
Hi !
I just came across this, and I find this behavior really misleading. It's too tempting to use something like `*ngIf` or `*ngFor` on `ag-grid-column`.
Do you plan to support this in the near future ?
