### ISSUE TITLE
enableRtlSupport 

### ISSUE THREAD

**Issue by TheILPlace** [ceolter/ag-grid-ng2#95]
Angular2 project.
    "ag-grid": "^7.0.2",
    "ag-grid-ng2": "^7.0.1",

getting warnings in chrome console
agGridNg2.js:164Grid property getBusinessKeyForNode does not exist on AgGridNg2
agGridNg2.js:164Grid property checkboxSelection does not exist on AgGridNg2
agGridNg2.js:164Grid property enableRtlSupport does not exist on AgGridNg2

**Comment by seanlandsman** [comment]
Thanks, will be fixed in the next release

**Comment by TheILPlace** [comment]
in the changed file, i didnt see a reference to the missing enableRtlSupport property
