### ISSUE TITLE
Output Variables for AgRendererComponent

### ISSUE THREAD

**Issue by sirhcybe** [ceolter/ag-grid-ng2#98]
I looked over the documentation but I do not see a way to output an event from an AgRendererComponent. What I would like to do is have a new row added to my grid when a button is clicked in my AgRendererComponent. But without an Output function I am not sure the best way to modify the grid's row data in response to the click event in the AgRendererComponent. Am I missing something?

I am thinking about using a service to interact between the two components but things would be simpler if there was a way to bubble the event out of the AgRendererComponent in to the component with the grid.

**Comment by seanlandsman** [comment]
The easiest thing to do would be to have a service that you can use as a bridge between your "parent" and child components, subscribing to events etc to respond to them.

The reason for this is that the parent component in this case is the grid component, not your "parent" component. We considered some sort bus etc to achieve what you're after, but given the service intermediary is a standard idiom and one of the suggested communication routes between components we decided not to (in the interests of not over-engineering things).

I hope this makes sense - let me know if you'd like more information around this

**Comment by sirhcybe** [comment]
Thanks, it does make sense. For the simple use case that I have, adding a whole separate service feels like overkill but I understand your reasoning and am ok with it.

**Comment by TheILPlace** [comment]
This is exactly what i did. but with a twist.
i created a button component to be used as a AgRendererComponent. 
i've put that button component in a shared module along with other renderers.

that button could do many actions. so i'm passing an object to that renderer via 
cellRendererParams  .

the button, once clicked will call a function in a Service (that is provided in the component that has the grid) and will pass along the object the button received, plus additional data (the rowdata for example)
in the service i can switch-case to understand what king of button it was, and decide what to do (including emitting an event)

**Comment by seanlandsman** [comment]
@TheILPlace @sirhcybe 

You can achieve this with gridOptions.context - take a look at:

Parent: https://github.com/ceolter/ag-grid-ng2-example/blob/master/systemjs_aot/app/from-component.component.ts
Child: https://github.com/ceolter/ag-grid-ng2-example/blob/master/systemjs_aot/app/child-message.component.ts

For an example of how this can be used

**Comment by aesopturtle** [comment]
@seanlandsman The links are dead. Do you have updated links? I need something similar too.

**Comment by seanlandsman** [comment]
@aesopturtle the new links are:

https://github.com/ceolter/ag-grid-angular-example/blob/master/systemjs_aot/app/dynamic-component-example/dynamic.component.ts
https://github.com/ceolter/ag-grid-angular-example/blob/master/systemjs_aot/app/dynamic-component-example/child-message.component.ts

thanks

**Comment by aesopturtle** [comment]
Thank you very much :)

**Comment by konidala** [comment]
Thanks a lot.
