### ISSUE TITLE
Not working with the latest Angular2 version 2.3.1

### ISSUE THREAD

**Issue by ssashok10** [ceolter/ag-grid-ng2#99]
I am using the latest Angular2 version 2.3.1 and it throws the below error. This grid was working fine with Angular2 version 2.1.x

```
Error		Build:Module '"I:/Angular2TestApp/node_modules/@angular/compiler/index"' has no exported member 'RuntimeCompiler'.	

File : I:\Angular2TestApp\node_modules\ag-grid-ng2\lib\ng2ComponentFactory.d.ts	3	
```

**Comment by seanlandsman** [comment]
What version of ag-grid-ng2 are you using?  The latest version should support 2.3.1

**Comment by ssashok10** [comment]
I made it working. All the errors that i faced was due to the inline cellRedererFramework code which is not supported with Ag-Grid V7. I have created a separate Angular2 component for cell rendering.
